### ISSUE TITLE
What do I search for to find this in the Asset Library (Godot v3.0.6.stable.official.8314054)

### ISSUE THREAD

**Issue by riverfr0zen** [touilleMan/godot-python#105]
I've searched for `python` and `godot-python` but I'm not getting any results in 'Templates' tab (which I'm assuming is the asset library--I'm new to Godot). I've checked Official, Community, and Testing in the Support filter. All other filters are as wide open as they can be.

**Comment by touilleMan** [comment]
You should use the `AssetLib` tab in Godot:
![image](https://user-images.githubusercontent.com/3187637/44119337-3b2c799e-a019-11e8-8e4d-3c11fb1cfaa4.png)

Otherwise, here is the link of the project in the asset library website: https://godotengine.org/asset-library/asset/179
