### ISSUE TITLE
"No "battery included" policy" for MicroPython, huh?

### ISSUE THREAD

**Issue by pfalcon** [touilleMan/godot-python#11]
From README:

> No "battery included" policy unlike CPython

Well, that's not true. We just don't include those gigantic truck-style lead-acid batteries, but small wearable LiPo ones ;-).

**Comment by touilleMan** [comment]
@pfalcon so "choose the size of your battery included" policy ? 😄

**Comment by razvanc-r** [comment]
What does this mean? How can we fix it? Use tractor battery? :P

**Comment by pfalcon** [comment]
To clarify, MicroPython follows most of general Python paradigms, and I (as a MicroPython comaintainers) personally always mention that "batteries included" policy is followed too. You can very easily see it if you compare MicroPython with small implementations of other languages, like Lua or JavaScript.

So, someone reading my or somebody else's writings stating that "batteries included" policy is followed, and README of this project which states it's not, may get confused and wonder who's got it right. Well, this ticket should explain that.

Otherwise, feel free to do with this ticket whatever you want.
