### ISSUE TITLE
Usage lerp with python godot

### ISSUE THREAD

**Issue by vaclavbenes** [touilleMan/godot-python#111]
Hi, can i use lerp(linear interpolation) with python syntax . I tried import numpy project and use external lib for linear interpolation , but there is some problem python 3.6.  

Btw is possible upgrade godot python 3.6 to python 3.7 ? Thank .

**Comment by touilleMan** [comment]
Hi,

Sorry for the delay, I lack time working on this project right now :'-(

> can i use lerp(linear interpolation) with python syntax . I tried import numpy project and use external lib for linear interpolation , but there is some problem python 3.6.

You should be able to install whatever module is compatible with python 3.6 with the pip shipped with the project.

> Btw is possible upgrade godot python 3.6 to python 3.7 ? Thank .

It should be trivial to do so: just modify the version specified in the git clone in the `platforms/*/SCsub` files (ex: https://github.com/touilleMan/godot-python/blob/master/platforms/x11-64/SCsub#L54)
PR welcome for this ;-)
