### ISSUE TITLE
Does Godot Python work cross-platform?

### ISSUE THREAD

**Issue by lukefisklennon** [touilleMan/godot-python#113]
Hi there!

This is probably a pretty basic question, but I just want to check that Godot Python works on all the usual platforms of Godot, and with all the same features. Are there any drawbacks?

Thanks so much.

**Comment by touilleMan** [comment]
Hi, yes Godot-Python is supposed to work cross platform on windows/linux/macOS. Mobile and web platforms are not supported yet.
