### ISSUE TITLE
Discuss how to import external python modules

### ISSUE THREAD

**Issue by jejay** [touilleMan/godot-python#115]
It would be nice to have a discussion in the README about importing external python modules, specifically ones that have native extensions themselves. I think using python modules is the main selling point of this project.

I already left a comment in #100 (the issue implies one method of importing modules) but since the issue is closed I opened this one here.

**Comment by touilleMan** [comment]
You're right about this, PR welcomed ;-)

**Comment by FeralBytes** [comment]
So is the solution to basically copy python packages over from the host to the lib folder in the hosted folder? That is how I did it for Linux? Will this same solution work for Windows or do I need a windows host for the correct package files?

**Comment by shayneoneill** [comment]
That would be a given, FeralBytes. Python packages can not be assumed to be locally installed at all , particularly in windows where Python isn't installed by default.

**Comment by apockill** [comment]
You can also use pips `--target` command, as shown here https://github.com/touilleMan/godot-python/issues/183

**Comment by thetoblin** [comment]
> So is the solution to basically copy python packages over from the host to the lib folder in the hosted folder? That is how I did it for Linux? Will this same solution work for Windows or do I need a windows host for the correct package files?

I'm trying to use `numba` through an Anaconda install on Ubuntu, and I'm having troubles importing python modules. I've copied the `numba` module folder from the `anaconda3` folder to the `addons/pythonscript/x11-64/lib` folder, which does not seem to work. I still get the error that there is no such module when trying to import.
