### ISSUE TITLE
SurfaceTool.commit() not working without paramerer.

### ISSUE THREAD

**Issue by jejay** [touilleMan/godot-python#127]
If you use SurfaceTool.commit() you get an error about the type of the objects you are supposed to give it. The docs state that the parameters are optional. If I give it an object, it works.

https://docs.godotengine.org/en/latest/classes/class_surfacetool.html#class-surfacetool-method-commit

Godot 3.1.1stable, godot-python 0.11.3 with CPython. Ubuntu.

**Comment by touilleMan** [comment]
Yes, optional parameters are not supported for the moment ;-)

duplicate of #27
