### ISSUE TITLE
RealBinder can only be used with floats

### ISSUE THREAD

**Issue by razvanc-r** [touilleMan/godot-python#13]
After adding `Vector3` and `GETSET` functions for properties (`x`, `y`, `z`) I discovered that if I do:

```py
a = Vector3()
a.x = 10 # this fails
a.x = 10. # this works
```

This most likely happens for all functions that expect `float` as a parameter, but are called with `int`.

**Comment by touilleMan** [comment]
should be fixed by 425e47d88fd863e19a24dc19a79d1a531cdbab50

**Comment by razvanc-r** [comment]
This still gives me an error. For some reason the incorrect `is_type` is called or something, I don't get it exactly because I tried putting a print statement inside of `RealBinder::is_type` and it doesn't get printed. I compiled with the fix and now I'm getting an error when Vector2.clamped is used.

**Comment by touilleMan** [comment]
I'll have a look this weekend

**Comment by razvanc-r** [comment]
Wait, it might be because these are header files and the object files didn't compile, let me check
