### ISSUE TITLE
Cannot set self.position.x/y for Area2D

### ISSUE THREAD

**Issue by JohnnyUrosevic** [touilleMan/godot-python#131]
Hello,

I was working on transcribing the "getting started" game to Python and I got to the part where I needed to restrict the player from moving outside of the screen. I wrote the following code

```
self.position.x = max(0, min(self.position.x, self.screensize.x))
self.position.y = max(0, min(self.position.y, self.screensize.y))
```

(side note, is there a way to use gdscript's clamp method?)

Yet when I run the scene, these two lines are completely ignored, even changing the right side to a constant makes them get ignored.

OS: Ubuntu
Godot Version 3.06

**Comment by touilleMan** [comment]
That's strange, given it's what is done with the pong example:
https://github.com/touilleMan/godot-python/blob/284f092d9f7893403f7af32cac5978532c0e7d21/examples/pong/paddle.py#L35-L38

Have you tried to run this example to see if it works as expected ?

**Comment by JohnnyUrosevic** [comment]
Trying to load that project into my Godot says that pong.py is missing and it has broken dependencies

**Comment by JohnnyUrosevic** [comment]
Update to this: ported my project over to my windows computer (Windows 10, Godot 3.06) and everything worked as intended. What a strange bug...

**Comment by touilleMan** [comment]
Maybe an environment variable messing with godot or python (normally the python interpreter we embed doesn't use environment variable for this reason, but we may have forget something...)
Another possibity would be that Godot was started from the wrong directory (typically doing `../godot`), this is something taken care of in theory (godot does a chdir in the project main directory as part of it init) but, again, who knows...

**Comment by JohnnyUrosevic** [comment]
Definitely seems like a strange bug. It might be the environment variables as now I went back on ubuntu and it works fine. ¯\_(ツ)_/¯

**Comment by kicksent** [comment]
If this issue is not reproducible on Ubuntu or Windows anymore can we close this? The creator of this issue is no longer seeing this issue on their machine.

**Comment by touilleMan** [comment]
@kicksent closing then ;-)

**Comment by Harshharsh2275** [comment]
> That's strange, given it's what is done with the pong example:
> https://github.com/touilleMan/godot-python/blob/284f092d9f7893403f7af32cac5978532c0e7d21/examples/pong/paddle.py#L35-L38
> 
> Have you tried to run this example to see if it works as expected ?

I have the same issue and tried your code but didn't work it just moves on
