### ISSUE TITLE
Build error on v0.20.0/master

### ISSUE THREAD

**Issue by curradium** [touilleMan/godot-python#139]
Hi, just tried to build godot-python from source on my machine, and got the following error:

```
$ scons platform=x11-64 release

scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
cython --fast-fail -3 pythonscript/godot/bindings.pyx

Error compiling Cython file:
------------------------------------------------------------
...
        
        return


    # void body_set_force_integration_callback(self, godot_rid body, godot_object receiver, godot_string method, godot_variant userdata,)
    def body_set_force_integration_callback(self, RID body  not None, Object receiver  not None, object method, object userdata  not None=Null,):
                                                                                                                                         ^
------------------------------------------------------------

pythonscript/godot/bindings.pyx:12019:138: undeclared name not builtin: Null
scons: *** [pythonscript/godot/bindings.c] Error 1
scons: building terminated because of errors.
```

This was on a 'standard' (i.e. no modifications to gcc or anything else that might be involved) Arch Linux install.

The command ```scons platform=x11-64 sample``` works fine, but neither of test, release, or example does.

**Comment by touilleMan** [comment]
Hi,

Thanks for pointing this out ;-)
This should be fixed by b3f4b9c33576da39bc24416bb5ac05332e8acccb

**Comment by curradium** [comment]
Yes, fixed, thank you! You weren't kidding about how much memory it takes up, it was over 6GB for me... I had to create a swap file to stop gcc OOMing!

**Comment by touilleMan** [comment]
Yup, this `bindings.c` is a really big baby... in fact release [0.20.1 has failed due to that](https://travis-ci.org/touilleMan/godot-python/jobs/644084179#L686) :'-(

However you can improve this a lot by using clang (it uses "only" 2GB)
