### ISSUE TITLE
Trying to get the example working, but errors just pop up

### ISSUE THREAD

**Issue by RDaneelOlivav** [touilleMan/godot-python#140]
Hi,

I am trying to have an example working with python, but cant get it to work
I'm using Godot 3.2 in Ubuntu 18.
When I open the pong example hay get the **broken dependencies issue**. And when opening anyway the project, then when installing the python asset, it give another error:

** the following files failed extraction from package:

res://pythonscript/osx-64-python/.gdignores:://pythonscript/osx-64.....
And 9984 more files.

Any idea?

I would like to make a working example for Godot 3.2 for everyone to be able to use this great asset. I want to use loads of python modules in Godot, so for sure I would love to mak esome tutorials on the matter.

But this issue is just to strange to make head or tails of it.

Any suggestion? Any procedure to have a working plug and play example?

Thanks in advance

**Comment by touilleMan** [comment]
Hi,

Have you build the godot-python before trying to open the demo example ? (you may have seen the examples and tests folders contains symlinks to the build dir, so nothing can work within the build)

```shell
$ scons platform=x11-64 sample=true example/pong
```

**Comment by RDaneelOlivav** [comment]
rdaneel (master) godot-python $ scons platform=x11-64 sample=true example/pong
scons: Reading SConscript files ...
  File "/home/rdaneel/KODAMA/godot_plugins/godot-python/SConstruct", line 101

    cooked.append(msvc or f"/{opt[1:]}")

                                      ^

SyntaxError: invalid syntax



Getting this error. I'm trying to understand how to use this plugin. Why d I have to compile it and when I get it compiled ( which seems I have an error ) how to install it in Godot? I'm a complete begginner in Godot Plugin developement andany help would be nice. I would love to use this plugin but I dont get it to even start. 

Thanks in advance

**Comment by touilleMan** [comment]
Hi,

I guess you're using Python 2.7 to run second. This project requires python
>= 3.6 and scons 3

You should be fine by doing
```
$ python3 -m venv venv
$ . ./venv/bin/activate
$ pip install scons
$ scons platform=x11-64
```

Le lun. 10 févr. 2020 à 08:48, RDaneelOlivav <notifications@github.com> a
écrit :

**Comment by RDaneelOlivav** [comment]
Ok, got it at least compiling with this setup script:



But Executing the tests, gave me this error:

> (py3venv) rdaneel (master) godot-python $ scons platform=x11-64 test
> scons: Reading SConscript files ...
> scons: done reading SConscript files.
> scons: Building targets ...
> curl -L https://github.com/GodotBuilder/godot-builds/releases/download/3.0_20180303-1/godot.x11.opt.debug.64 -o platforms/x11-64/godot.x11.opt.debug.64 && chmod 750 platforms/x11-64/godot.x11.opt.debug.64
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100   612    0   612    0     0   1313      0 --:--:-- --:--:-- --:--:--  1310
> 100 26.2M  100 26.2M    0     0  2075k      0  0:00:12  0:00:12 --:--:-- 3067k
> SymLinkAction(["build/main"], ["build/pythonscript-x11-64"])
> /home/rdaneel/KODAMA/tests_for_python3_plugin_godot/godot-python/platforms/x11-64/godot.x11.opt.debug.64 --path /home/rdaneel/KODAMA/tests_for_python3_plugin_godot/godot-python/tests/bindings
> ERROR: _load_settings_text: Condition ' config_version > 3 ' is true. returned: ERR_FILE_CANT_OPEN
>    At: core/project_settings.cpp:495.
> ERROR: _load_settings_text_or_binary: Couldn't load file '/home/rdaneel/KODAMA/tests_for_python3_plugin_godot/godot-python/tests/bindings/project.godot', error code 12.
>    At: core/project_settings.cpp:519.
> Error: Could not load game path '.'.
> scons: *** [tests/bindings] Error 255
> scons: building terminated because of errors.

Whats doing this exactly? Because it might be the way I have Godot installed? Could you enlight me here? I have my godot like just an "Godot_v3.2-stable_x11.64", its not even installed.

We are getting there ;), just a small push more :), could you help me there? This way we will have a simplified Ubuntu 18 example.

**Comment by touilleMan** [comment]
The version of Godot downloaded by scons to run the test is too old (3.0,
it should be 3.2)

I thought we had already fixed that... You should check in the
`platform/<platform>/Scsub` file to download the right version

Le mer. 12 févr. 2020 à 10:40, RDaneelOlivav <notifications@github.com> a
écrit :

**Comment by RDaneelOlivav** [comment]
Its getting "https://github.com/GodotBuilder/godot-builds/releases/download/3.0_20180303-1"

But I'm not very familiar with this SCub system. Where do we define this env variables? And where do we have to change it to 3.2?

**Comment by cridenour** [comment]
You can set the base URL in the [SConstruct file](https://github.com/touilleMan/godot-python/blob/master/SConstruct) - but unfortunately the GodotBuilder repo seems to have stopped with 3.0.3. 

Which means, you'll want to provide your own binary file - shown here in the README.

https://github.com/touilleMan/godot-python#using-a-local-godot-version

**Comment by touilleMan** [comment]
I've created #148 to track the issue to update downloaded Godot version ;-)

**Comment by RDaneelOlivav** [comment]
Tried using the binary:
scons platform=x11-64 godot_binary=~/Godot_v3.2-stable_x11.64
scons: Reading SConscript files ...
  File "~/tests_for_python3_plugin_godot/godot-python/SConstruct", line 101

    cooked.append(msvc or f"/{opt[1:]}")

                                      ^

SyntaxError: invalid syntax

Any ideas why?

As for updating the version of Godot #148 hw can I contribute to that? Would love to help.

**Comment by touilleMan** [comment]
The project requires Python >= 3.6
The easiest way to ensure scons runs with the right python version is to create a virtual env and install scons from there:
```shell
$ cd <my_godot_python_dir>
$ python3 --version  #make sure you have the correct python on your system
[...]
$ python3 -m venv venv
$ . ./venv/bin/activate  # Remember to activate the venv for your shell each time you need to use scons !
$ pip install scons
[...]
$ scons ...  
```

see https://github.com/touilleMan/godot-python#create-the-virtual-env
