### ISSUE TITLE
Update downloaded godot version for running tests/examples

### ISSUE THREAD

**Issue by touilleMan** [touilleMan/godot-python#148]
Currently Godot 3.0 is downloaded and used to run the tests/exemples (typically when doing `scons platform=x11-64 examples/pong`).

However it's a very old version which is no longer compatible with the current `godot.project` format (see https://github.com/touilleMan/godot-python/issues/140#issuecomment-585118100). Hence we should update the code to download Godot version 3.2

Interesting places to investigate:

https://github.com/touilleMan/godot-python/blob/61e4adc7b278828cd7a30656a58ac2e319bc505a/SConstruct#L40-L44

And for each platform:

https://github.com/touilleMan/godot-python/blob/61e4adc7b278828cd7a30656a58ac2e319bc505a/platforms/x11-64/SCsub#L19-L27

**Comment by curradium** [comment]
Same issue as in #142, and I've partially fixed it as I mentioned in there, I've been too busy to do the necessary followup. I'll make time tonight/in the week to follow up on it. :)

**Comment by touilleMan** [comment]
thanks @curradium ;-)

**Comment by touilleMan** [comment]
fixed by #163
