### ISSUE TITLE
test fails with "Cannot load godot python module"

### ISSUE THREAD

**Issue by chrisgraf** [touilleMan/godot-python#154]
I followed the instructions in the readme and could build the release but when executing the test it fails as follows. How can I further debug the issue?

 % scons platform=x11-64 test   
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
cd platforms/x11-64 && curl -L https://downloads.tuxfamily.org/godotengine/3.2/Godot_v3.2-stable_x11.64.zip -o Godot_v3.2-stable_x11.64.zip && unzip Godot_v3.2-stable_x11.64.zip

Archive:  Godot_v3.2-stable_x11.64.zip
  inflating: Godot_v3.2-stable_x11.64  
SymLinkAction(["build/main"], ["build/pythonscript-x11-64"])
/home/graf/landscapelab/godot-python-0.20.2/platforms/x11-64/Godot_v3.2-stable_x11.64 --path /home/graf/landscapelab/godot-python-0.20.2/tests/bindings
Godot Engine v3.2.stable.official - https://godotengine.org
OpenGL ES 3.0 Renderer: AMD Radeon RX 5700 (NAVI10, DRM 3.33.0, 5.3.0-40-generic, LLVM 10.0.0)
 
ERROR: godot_gdnative_init: Cannot load godot python module
   At: pythonscript/pythonscript.c:199.
ERROR: _load: No loader found for resource: res://main.py.
   At: core/io/resource_loader.cpp:285.
ERROR: poll: res://main.tscn:3 - Parse Error: [ext_resource] referenced nonexistent resource at: res://main.py
   At: scene/resources/resource_format_text.cpp:440.
ERROR: load: Failed to load resource 'res://main.tscn'.
   At: core/io/resource_loader.cpp:208.
ERROR: _load: Failed loading resource: res://main.tscn.
   At: core/io/resource_loader.cpp:278.
ERROR: start: Failed loading scene: res://main.tscn
   At: main/main.cpp:1864.
WARNING: cleanup: ObjectDB Instances still exist!
   At: core/object.cpp:2071.

**Comment by touilleMan** [comment]
Hi @chrisgraf,

It seems the godot-python cannot load the `_godot` python module, can you make sure there is a `_godot.so` file in the `build/main/pythonscript/python3.7/site-packages/` directory ?

What you could do to debug further is to add print into the `pythonscript/_godot.pyx` file, then rebuild&run to see if the module gets loaded then crash or if it cannot be loaded at all (I had plenty of trouble with subtle circular dependencies involving `_godot ` and `godot._hazmat` that end with a fine compilation but the `_godot` module not being able to load...)

**Comment by chrisgraf** [comment]
Thanks for your Feedback!
I made sure the _godot.so file is there. The directory is build/main/pythonscript/lib/python3.7/site-packages - just to make sure.

I also added a print as first line and another after the imports in the _godot.pyx file. Again it built without complains but when running the test the same error message appears. None of the prints get printed so I guess the library can't be loaded at all. But how can I investigate the reason?

**Comment by touilleMan** [comment]
Ok I got the bad apple: c2f80e14c0f2b51befafa7a3ae364091f0cfc076

with this commit, `_godot.so` requires `libpythonscript.so` but cannot find it

Quick workaround (until we fix this for good !) is to provide `libpythonscript.so`'s path with LD_LIBRARY_PATH: 
```shell
$ env LD_LIBRARY_PATH="/home/emmanuel/projects/godot-python/test-issue-154/godot-python/build/main/pythonscript/"   /home/emmanuel/projects/godot-python/test-issue-154/godot-python/platforms/x11-64/Godot_v3.2-stable_x11.64 --path /home/emmanuel/projects/godot-python/test-issue-154/godot-python/tests/bindings
```

**Comment by rac0316** [comment]
I'm having the same issue with a fresh mac osx-64 build from the master branch. Does something similar have to happen to get it running?

I tried this on my mac (pointing to `libpythonscript.dylib` instead of `libpythonscript.so`), but it doesn't work:

`env LD_LIBRARY_PATH="/Users/rac0316/Games/godot-python/build/osx-64/pythonscript" /usr/local/bin/godot --path /Users/rac0316/Games/godot-python/tests/bindings`

**Comment by rac0316** [comment]
Should have played around 5 more minutes before posting - figured it out! Mac uses `DYLD_LIBRARY_PATH`, not `LD_LIBRARY_PATH `.  So for Mac, needs to look similar to this:

env DYLD_LIBRARY_PATH="/Users/rac0316/Games/godot-python/build/osx-64/pythonscript" /usr/local/bin/godot --path /Users/rac0316/Games/godot-python/tests/bindings

**Comment by rac0316** [comment]
Now i'm at the point where I see the following behaviors - tests start to run, but test_arr.py gets stuck, and then errors out.

Also, can't run the pong example using this method - would it just be a path to the pong example folder?

**Comment by chrisgraf** [comment]
As there is a new release now available compiling it myself currently is not necessary - for me this issue is resolved

**Comment by touilleMan** [comment]
Well I hope from now on the release schedule will be a bit more regular that it used to be ;-)
