### ISSUE TITLE
No stdout or stderr

### ISSUE THREAD

**Issue by matheus2740** [touilleMan/godot-python#158]
Hi, either I'm doing something wrong or there doesn't seem to be a way to see stdout or stderr?
I tried using print, sys.stdout.write, sys.stderr.write and was unable to see anything in godot's output monitor. Also, syntax errors and exceptions don't appear anywhere, the file just gets ignored. is there a editor window I'm not looking at or some setting I need to tick? Kinda unusable if I can't see exceptions or output...
Btw, I tried on a new blank project and also the provided pong example.

**Comment by matheus2740** [comment]
I just realized the output is there at the console window (the cmd window that opens alongside godot, not inside the engine).

**Comment by touilleMan** [comment]
Hi @matheus2740,

Yep, the stdout/stderr is not yet redirected to the godot console.

This feature was present in version 0.11 but hadn't been backported to 0.20 yet.
If you're interested on working on this, you should take a look at this file from v0.11:
https://github.com/touilleMan/godot-python/blob/1b245491fe4436a472584a4a44f8cb4fb4add630/pythonscript/embedded/godot/hazmat/io.py#L44-L52

And uncomment this part:
https://github.com/touilleMan/godot-python/blob/a95ed14f6e53ae4eb59e6bd03efb0db90b070bc6/pythonscript/_godot.pyx#L46-L49

**Comment by matheus2740** [comment]
fixed by #176

**Comment by apockill** [comment]
Ahh, I should have read this thread yesterday. I will take a look at the command window next time- I've been trying to update from v0.11 to v0.30 and I was confused why simple prints weren't working!
