### ISSUE TITLE
Can't build test file

### ISSUE THREAD

**Issue by Kolterdyx** [touilleMan/godot-python#164]
when I execute this command:
`scons platform=x11-64 test`

I get this error:
```
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
scons: *** Do not know how to make File target `test' (/home/kolterdyx/godot-python/test).  Stop.
scons: building terminated because of errors.
```
I have followed all the steps for my distro (Parrot Os, similar to Debian) and I don't know how to solve this

**Comment by touilleMan** [comment]
The README is not up to date, thanks for pointing this out ;-)

The command to run is `scons platform=x11-64 tests`
