### ISSUE TITLE
Can't connect to HTTPS URL because the SSL module is not available.

### ISSUE THREAD

**Issue by Kolterdyx** [touilleMan/godot-python#167]
I am trying to use the `googletrans` module on godot-python, and when I execute the program I get this error:

> Traceback (most recent call last):
>   File "/media/kolterdyx/Seagate/Files/Programming/Games (Godot)/app/pythonscript/x11-64-cpython/lib/python3.6/site-packages/urllib3/connectionpool.py", line 659, in urlopen
>     conn = self._get_conn(timeout=pool_timeout)
>   File "/media/kolterdyx/Seagate/Files/Programming/Games (Godot)/app/pythonscript/x11-64-cpython/lib/python3.6/site-packages/urllib3/connectionpool.py", line 279, in _get_conn
>     return conn or self._new_conn()
>   File "/media/kolterdyx/Seagate/Files/Programming/Games (Godot)/app/pythonscript/x11-64-cpython/lib/python3.6/site-packages/urllib3/connectionpool.py", line 946, in _new_conn
>     "Can't connect to HTTPS URL because the SSL module is not available."
> urllib3.exceptions.SSLError: Can't connect to HTTPS URL because the SSL module is not available.

I have tried installing `pyopenssl` but that haven't seem to work

If you're asking why am I using google translate on a game, it's because it's not a game, it's an app I have to do for school and I am using godot since I am not able to do it anywhere else :P

**Comment by OFTekk** [comment]
I had same problem with Python at all. Under windows. It was because of "libssl*.dll" was not exposed to Python _ssl module on PATH. May be that this is same problem on your side.

**Comment by touilleMan** [comment]
Now that python is provided by the awesome python-standalone-build project, libssl should be correctly provided \o/
