### ISSUE TITLE
Remove __pycache__ directory from distributions / releases

### ISSUE THREAD

**Issue by matheus2740** [touilleMan/godot-python#177]
I noticed while downloading from the asset store that it downloads a very large package with a lot of __pycache__ directories. I guess we need to remove them from the builds.

**Comment by touilleMan** [comment]
I agree, last release was surprisingly big (~700mo for the 4 platforms combined)

However I'm not sure the __pycache__ add that much space (I've counted ~7.7mo for the whole standard CPython library). On the other hand not providing __pycache__ is no big deal (I have no idea how much is improve the load time compare to regular .py files), may it's even better to remove the .py and only keep the .pyc... do you have any resources on this ?

Another optimization that would make a big change is to zip the entire CPython standard library (that's what used to be done in version 0.10.x)

**Comment by matheus2740** [comment]
Unfortunately I don't think it's possible to distribute only .pyc, but I maybe wrong. Another option is to cython compile the whole stdlib, that may even buy a little performance.

**Comment by matheus2740** [comment]
also, looking at some packages in 'pythonscript/osx-64/lib/python3.7' there's a lot of stuff we can just 'rm', like:
```
2.4M	tkinter
4.9M	idlelib
 59M	test  <<< python test suite. we definitely dont need this
9.5M	__pycache__
 12M	config-3.7m-darwin <<< can we delete this? 
```
That's 87M that can easily be fixed with a simple `rm` in the scons build script. That would reduce the macos distribution from 147M to 60M, a substantial improvement.

**Comment by touilleMan** [comment]
I've made a couple of commits to fix this ;-)

Now the Python standard lib is contained in a zip, the test package and __pycache__ stuff get entirely removed
