### ISSUE TITLE
pythonscript.gdnlib is wrong on mac os in asset store distribution

### ISSUE THREAD

**Issue by matheus2740** [touilleMan/godot-python#178]
Line says:
`OSX.64="res://addonspythonscript/osx-64/libpythonscript.dylib"`
When it should be:
`OSX.64="res://addons/pythonscript/osx-64/libpythonscript.dylib"`

(there is a slash missing)

**Comment by touilleMan** [comment]
nice catch !
fixed by 3bc6241
