### ISSUE TITLE
Certain imports are unavailable in v0.30.0

### ISSUE THREAD

**Issue by apockill** [touilleMan/godot-python#193]
Hi guys, this might very well be user error, but here are the symptoms of my issue. 

I am trying to upgrade from v0.11.2 to v0.30.0, the version on the AssetLib. 

```python
from godot.bindings import Camera2D, InputEventMouseButton
``` 

fails with 

```bash
ImportError: cannot import name 'Camera2D' from 'godot.bindings' (/path/shortened/for/brevity/creepycrawlai/addons/pythonscript/x11-64/lib/python3.7/site-packages/godot/bindings.so)
```

I have found that at least `Camera2D` and `InputEventMouseButton` have this problem (they cannot be imported using `from godot import` either.  

Any help would be greatly appreciated! Thank you for updating the version on the AssetLib.

**Comment by filantus** [comment]
Hi! I think i have similar problem - https://github.com/touilleMan/godot-python/issues/191
