### ISSUE TITLE
Attempts to download wrong cpython version on Python 3.8.3

### ISSUE THREAD

**Issue by MaxBleggi** [touilleMan/godot-python#209]
So I've been trying to use godot-python for the past couple weeks to put some of my AI work into a game I'm working on. I've tried nearly everything to get it to work on my project from re-installing python and everything else, using different versions, Mac and Windows. Nothing has worked.

Attempted to do this, but it doesn't work: https://www.reddit.com/r/godot/comments/e56oae/pythongodot_setup_tutorial/
now I most recently tried to clone the repository and build it on my mac. I have python 3.8.3 and was following directions on the readme. 
I get this 
<img width="1279" alt="Capture d'écran 2020-06-28 12 19 05" src="https://user-images.githubusercontent.com/12599003/85952931-ae325f80-b93a-11ea-937d-33d6c501d14e.png">

If anyone could please offer some assistance, I'd greatly appreciate it as well. I've tried to research and attempt every guide I could find over the past 2 weeks. I can't get this to work. But that is unrelated to the issue above

**Comment by matheus2740** [comment]
Hey @MaxBleggi you don't need to have python pre installed, godot-python will download an interpreter from github/python-build-standalone and put it on your addons folder. I think from your error message the interpreter godot-python is trying to download does not exist on github anymore. can you please `ls /build/osx-64/cpython_prebuild` and paste it here?

**Comment by MaxBleggi** [comment]
Thank you for the rapid response!

In response to your request, I've attached a screenshot of it. I cloned the project and am up to date.
<img width="1280" alt="Capture d'écran 2020-06-29 08 12 57" src="https://user-images.githubusercontent.com/12599003/86004013-a5946480-b9e0-11ea-826e-75b96bbeb428.png">



I also retried to download it from the asset store. My steps. 
Delete Godot install, 
install newest version of godot, 
create new test project,
download from asset store, 
restart godot,
I open godot but nothing is different and I can't see use or look at python files,
copy&paste the contents of ~/pythonscript/osx-64-pypy/ into my root folder,
restart godot,
nothing new.
<img width="1280" alt="Capture d'écran 2020-06-29 08 26 23" src="https://user-images.githubusercontent.com/12599003/86005699-f4db9480-b9e2-11ea-97f4-d15a52bd59ee.png">



Are these the correct steps? Other than detecting files in the editor, I've also tried to run some scenes before. It would always error like it would if I didn't have godot-python

**Comment by Zireael07** [comment]
IIRC asset store version of the plugin is very old? Might require manually installing Python?

**Comment by matheus2740** [comment]
No, touilleman released the new version (0.40) on the asset store too. Also, latest version of Godot is 3.2.2 which was release jsut last week, and I don't think it's tested. You should probably go for 3.2.1 at least for now. Buuuut apparently you downloaded the pypy version which is pretty ancient and not supported anymore. @touilleMan I think you remove it from the store.

Try following these steps:
* Download Godot 3.2.1
* Create a new project
* Inside the editor itself, go to the "AssetLib" tab (right next to Script on the top) and search for python.
* Download and install from the editor itself. Make sure to download version 0.40 NOT the pypy version.

**Comment by touilleMan** [comment]
@matheus2740 you're right, I sohuld remove pypy version but it's not possible with the asset store :(
I've updated the description to explain the module is deprecated though

**Comment by MaxBleggi** [comment]
@matheus2740 thank you for all of the help and time, I appreciate it. I will try out the steps as you provided them after I write this post.

I believe I have found the reason behind my weeks of headaches. 
This is from Godot 3.2.2 on Mac

<img width="1280" alt="Capture d'écran 2020-06-29 14 32 10" src="https://user-images.githubusercontent.com/12599003/86042827-ba3f1f80-ba15-11ea-810f-0e9776ad4a74.png">


This is from Godot 3.1.2 on Windows
![godot3 1 2_windows](https://user-images.githubusercontent.com/12599003/86042871-d347d080-ba15-11ea-9a8a-8a61ab8edc8b.JPG)

So for some reason, either because of the platform or version, the correct version is inaccessible from the AssetLib. The only reason I caught this was because I had deleted my old Godot on my mac. So I was confused when I saw two versions available. I thought the peppy was the only option available.

**Comment by MaxBleggi** [comment]
> Try following these steps:
> 
> * Download Godot 3.2.1
> * Create a new project
> * Inside the editor itself, go to the "AssetLib" tab (right next to Script on the top) and search for python.
> * Download and install from the editor itself. Make sure to download version 0.40 NOT the pypy version.

ahh Yes finally it is working. Thank you. All of my problems were from the issue in my previous comment. It was the pypy version

**Comment by touilleMan** [comment]
@MaxBleggi sorry for your headaches :(

The trouble comes from Godot AssetLib that is really too crude at the moment (I wanted to give a hand to improve it... but it's made in PHP so I quickly gave up :trollface: )

So the trouble comes from the fact the AssetLib doesn't handle versioning: updating a library means editing it so you cannot install version n if version n+1 has been released.

On the other hand, AssetLib allow you to specify for which version of Godot your module is for. This is especially useful considering the classes exposed by Godot through the GDNative API can change between version which can lead to segfaults !

This is what happened when [SceneTree.quit got add a exit_code parameter](https://docs.godotengine.org/en/stable/classes/class_scenetree.html#class-scenetree-method-quit), hence Godot version 3.2 is incompatible with 3.1.

Fast forward to now, were we have in the AssetLib:
- `PythonScript` which correspond to Godot-Python 0.40.0 released for Godot 3.2
- `PythonScript-Pypy` which is still Godot-Python 0.11.3 released for Godot 3... hence considered compatible with any Godot >= 3.0 !

Note: It's easy to do finger-pointing toward the AssetLib here, but 1) let's all be thankful it exists in the first place 😄  2) keep in mind Godot-Python needs are much more complicated than 99% of the modules on the AssetLib so YMMV

**Comment by MaxBleggi** [comment]
@touilleMan Don't worry c'est la vie parfois ;) Thank you for being so responsive and helpful. The reason I hadn't posted earlier is because I am so used to using repositories that are very old and it usually takes a long time for a response, by which time, I've usually moved on. On the bright side, thank you for the excellent resource. With this project, I wouldn't be able to import my AI into Godot. And GDScript doesn't allow for circular referencing, hence why I am willing to postpone my project by 3 weeks because this project is that important. So thank you. My project working... at lease for now haha.

I suspect that this won't be a problem for anyone as long as they are updated to the latest version of Godot. I didn't think 3.1.* made a difference before this.

**Comment by matheus2740** [comment]
Max, I think you confused 3.1.x with 3.2.1 :) 
What I said is that 3.2.2 is brand new and may contain errors with godot-python,
the version I'm using currently is 3.2.1.
