### ISSUE TITLE
Errors when execute test/example

### ISSUE THREAD

**Issue by Tedezed** [touilleMan/godot-python#21]
Hi!, I would like to try Godot Engine with Python to treat 3D objects, the compilation seems to finish correctly, but when running test/example I encounter the following errors:

`$ make test`
`$ make run_example`

Errors:
```
cd tests/bindings && /home/544GH5/Godot-src/godot-python/godot/bin/godot* 
GLES3: max extensions: 165
GLES3: max ubo light: 409
GLES3: max ubo reflections: 455, ubo size: 144
ERROR: load: No loader found for resource: /home/544GH5/Godot-src/godot-python/godot/bin/godot.x11.tools.64.llvm
   At: core/io/resource_loader.cpp:213.
ERROR: start: Failed loading scene: /home/544GH5/Godot-src/godot-python/godot/bin/godot.x11.tools.64.llvm
   At: main/main.cpp:1462.
WARNING: cleanup: ObjectDB Instances still exist!
   At: core/object.cpp:1910.
ERROR: cleanup: There are still MemoryPool allocs in use at exit!
   At: core/dvector.cpp:69.
```

`/godot/bin$ ls`
```
godot.x11.tools.64  godot.x11.tools.64.llvm  libpython3.6m.so.1.0
```

Thx!

**Comment by touilleMan** [comment]
Command `cd tests/bindings && /home/544GH5/Godot-src/godot-python/godot/bin/godot*` was misleading:
`godot*` should expand to `godot.x11.tools.64`, but given you compiled godot two times you end up with ``godot.x11.tools.64 godot.x11.tools.64.llvm`. Which means godot tries to open `godot.x11.tools.64.llvm` as a godot project...

I'm going to correct the README to be more clear about this :+1:

**Comment by Tedezed** [comment]
It works perfectly in `/godot-python/` with `cd tests/bindings && /home/544GH5/Godot-src/godot-python/godot/bin/godot.x11.tools.64`

Thx! :+1:
