### ISSUE TITLE
When could we expect godot-python can work with Godot4?

### ISSUE THREAD

**Issue by oneshotyj** [touilleMan/godot-python#215]
I like this project and have tried to compile and use with Godot4(under developing), but did not get lucky even during GDnative initialize phase. When can we get a version to try on Godot4 ? @touilleMan

**Comment by touilleMan** [comment]
Hi @oneshotyj !

Godot 4 is currently a moving target (a lot of things are changing, especially the GDNative API) so it's basically pointless to port Godot-Python for the moment.

My plans are to focus on Godot 3 for the moment (I'm also contributing to Godot, so all the quirks I encounter working on Godot 3 will provide improvements for Godot 4 ^^), then switch to Godot 4 when a beta is announced.
