### ISSUE TITLE
godot-python does not show in Godot 3.2.2 asset ?

### ISSUE THREAD

**Issue by WilliamTambellini** [touilleMan/godot-python#218]
Unless I missed something, I dont see godot-python in the asset store of 3.2.2 (site godotengine.org).
I see that page though: 
https://godotengine.org/asset-library/asset/179
I guess I can of course just download and install manually.
Has godot-python been tested with 3.2.2 ?
Kind

**Comment by touilleMan** [comment]
Godot has just been tested with 3.2.2 #222 😄 

You should be able to see the PythonScript plugin just fine from the AssetLib menu, for instance on Windows10 64bits with Godot 3.2.2:
![image](https://user-images.githubusercontent.com/3187637/88464016-90173b00-ceb7-11ea-9c9f-f606dfd84acb.png)

You may have noticed that the asset page (https://godotengine.org/asset-library/asset/179) specify the plugin is for Godot 3.2 so it should be available to all 3.2.x versions (and if not the case it's an issue on Godot side ^^)

**Comment by touilleMan** [comment]
I'm closing the issue, feel free to re-open it if I missed something ;-)
