### ISSUE TITLE
pythonscriptcffi initialization code failed

### ISSUE THREAD

**Issue by razvanc-r** [touilleMan/godot-python#22]
On ubuntu 17.04. With your master branch. Was I supposed to use the beta release from the release tab?!

Saw your beta release on twitter :D! Nices!! Well, I compiled with latest godot master branch (ref. *afbb5261e660acf08dd62f698d353e95fc7fb6bb*), but on running godot I get:

```
modules/pythonscript/py_script.cpp:27:_bind_methods
modules/pythonscript/py_language.cpp:284:PyLanguage     (93900151122192)
modules/pythonscript/py_language.cpp:20:init    (93900151122192)
Traceback (most recent call last):
  File "<init code for 'pythonscriptcffi'>", line 3341, in <module>
  File "<init code for 'pythonscriptcffi'>", line 3312, in __init__
  File "<init code for 'pythonscriptcffi'>", line 2956, in get_global_constansts
  File "<init code for 'pythonscriptcffi'>", line 2559, in godot_dictionary_to_pyobj
TypeError: expected a cdata struct/union/array object

From: pythonscriptcffi
compiled with cffi version: 1.10.0
_cffi_backend module: '/home/razvan/.local/lib/python3.6/site-packages/_cffi_backend.cpython-36m-x86_64-linux-gnu.so'
sys.path: ['/usr/lib/python36.zip', '/usr/lib/python3.6', '/usr/lib/python3.6/lib-dynload', '/home/razvan/.local/lib/python3.6/site-packages', '/usr/local/lib/python3.6/dist-packages', '/usr/lib/python3/dist-packages']

function pythonscriptcffi.pybind_init_sys_path_and_argv() called, but initialization code failed.  Returning 0.
ERROR: init: Method/Function Failed.
   At: modules/pythonscript/py_language.cpp:29.
modules/pythonscript/py_language.cpp:97:~PyLanguage     (93900151122192)
```

**Comment by touilleMan** [comment]
> Was I supposed to use the beta release from the release tab?!

Yes, building the project from the sources is not really streamline so far

>   File "<init code for 'pythonscriptcffi'>", line 2559, in godot_dictionary_to_pyobj

This function [has been removed](https://github.com/touilleMan/godot-python/commit/a2318fa0ef98f194688faf3b3d09b1bcf1e72e19#diff-bcce765dd14053bb1ff157a487bf2692R12), are you sure your `godot-python` repo is up to date ?

**Comment by razvanc-r** [comment]
Maybe there was some interference with an older compile. Running grep on the files did treturn a match:

```
 $ grep godot_dictionary_to_pyobj $(find -type f)
Binary file ./pythonscript/cffi_bindings/pythonscriptcffi.gen.x11.tools.64.o matches
```

 I'm trying compile after `make clean` now with latest commits

**Comment by razvanc-r** [comment]
Yah, it was an older compilation issue :+1:
