### ISSUE TITLE
Upgrade tests to godot 3.2.2

### ISSUE THREAD

**Issue by WilliamTambellini** [touilleMan/godot-python#220]
When running regtests, the master branch still downloads 3.2.1:  
$ scons platform=x11-64 test
scons: Reading SConscript files ...
3.6.11 (default, Jun 29 2020, 05:15:03) 
[GCC 5.4.0 20160609]
scons: done reading SConscript files.
scons: Building targets ...
Download&extract https://downloads.tuxfamily.org/godotengine/3.2.1/Godot_v3.2.1-stable_x11.64.zip
...

**Comment by touilleMan** [comment]
That's a really good point !

I've created PR #222 to address this

I've also added the possibility to specify a version of godot (by passing parametr `godot_binary=3.2.2`) to test against that would be automatically downloaded if needed ^^
