### ISSUE TITLE
Can't use get_node() 

### ISSUE THREAD

**Issue by HalfL1fe3** [touilleMan/godot-python#229]
Hi! 
I was using godot-python to recognize speech for my game, but this line in my code gives an error:
`lantern = godot.bindings.Node.get_tree("res://Spatial.tscn").get_root().get_node("../Lantern")`
The error:
 ```
Traceback (most recent call last):
  File "build\windows-64\pythonscript\_godot_script.pxi", line 188, in _godot.pythonscript_script_init
  File "G:\Gadget test\addons\pythonscript\windows-64\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "G:/Gadget test\speaker.py", line 27, in <module>
    lantern = godot.bindings.Node.get_tree("res://Spatial.tscn").get_root().get_node("../Lantern")
TypeError: descriptor 'get_tree' for 'godot.bindings.Node' objects doesn't apply to a 'str' object
```
I've also tried to use this variants:
`lantern = godot.Node.get_tree("res://Spatial.tscn").get_root().get_node("../Lantern")`
_This is the same to first variant_

`lantern = godot.Node.get_tree().get_root().get_node("../Lantern")`
_This says that get_tree needs an argument_

`lantern = godot.Node.get_node("../Lantern")`
_This variant says that get_node doesn't take 'str' arguments_

If you don't know how to fix it, you can say another solutions to import a node from the active scene

**Comment by touilleMan** [comment]
Hi @HalfL1fe3 (really cool nickname btw ^^) !

`godot.bindings.Node` refers to the Node class, so you cannot directly call method on it. It is pretty similar to this simple Python code:
```python
>>> class Foo:
...   def meth(self):
...     return 42
...
>>> Foo.meth()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: meth() missing 1 required positional argument: 'self'
>>> foo = Foo()
>>> foo.meth()
42
```

So you should be doing `self.get_node("../Lantern")` from a method of your exposed class:
```python
@exposed
class Speaker(Node):
    def _ready(self):
        self.lantern_node = self.get_node("../Lantern")
```

**Comment by HalfL1fe3** [comment]
Hello, @touilleMan. Thanks)
I wrote the code like you said, but now it just doesn't write anything. It starts the debug process, then it ends and that's all. It dosen't even display the game window, I've tried to run the full project or the active scene and nothing helpes.

**Comment by touilleMan** [comment]
Can you provide a minimal project so that I can reproduce the trouble on my side ?

**Comment by HalfL1fe3** [comment]
I have this script:
`import os
import time
import speech_recognition as sr
from fuzzywuzzy import fuzz
import pyttsx3
import datetime
from godot import exposed, Node

# настройки
opts = {
	"alias": ('ассистент','гаджет','робот','помощник','компьютер','сири',
			  'алиса','машина'),
	"tbr": ('скажи','расскажи','покажи','сколько','произнеси','отметь'),
	"cmds": {
		"ctime": ('текущее время','сейчас времени','который час'),
		"stupid1": ('расскажи анекдот','рассмеши меня','ты знаешь анекдоты'),
		"houseplan": ('планировка здания','план здания','карта комнаты',
					  'чертежи здания','где цель'),
		"findthings": ('на карте','просканируй местность',
					   'цели поблизости','опасные места'),
		"sms": ('сообщения','план на сегодня','задания рядом'),
		"lantern": ('включи фонарик','освети путь','включи лампу','включи свет'),
		"stop": ('стоп','остановись')
		}
}

@exposed
class Lantern(Node):
	def _ready(self):
		self.lantern_node = self.get_node("../Lantern")
lantern = Lantern()._ready().lantern_node
 
# функции
def speak(what):
	print( what )
	speak_engine.say( what )
	speak_engine.runAndWait()
	speak_engine.stop()
 
def callback(recognizer, audio):
	try:
		voice = recognizer.recognize_google(audio, language = "ru-RU").lower()
		print("[log] Распознано: " + voice)
   
		if voice.startswith(opts["alias"]):
			# обращаются к ассистенту
			cmd = voice
 
			for x in opts['alias']:
				cmd = cmd.replace(x, "").strip()
		   
			for x in opts['tbr']:
				cmd = cmd.replace(x, "").strip()
		   
			# распознаем и выполняем команду
			cmd = recognize_cmd(cmd)
			execute_cmd(cmd['cmd'])
 
	except sr.UnknownValueError:
		print("[log] Голос не распознан!")
	except sr.RequestError as e:
		print("[log] Неизвестная ошибка, проверьте интернет!")
 
def recognize_cmd(cmd):
	RC = {'cmd': '', 'percent': 0}
	for c,v in opts['cmds'].items():
 
		for x in v:
			vrt = fuzz.ratio(cmd, x)
			if vrt > RC['percent']:
				RC['cmd'] = c
				RC['percent'] = vrt
   
	return RC
 
def execute_cmd(cmd):
	if cmd == 'ctime':
		# сказать текущее время
		now = datetime.datetime.now()
		speak("Сейчас " + str(now.hour) + ":" + str(now.minute))
   
	elif cmd == 'stupid1':
		# рассказать анекдот
		speak("Мой разработчик не научил меня анекдотам")
	
	elif cmd == 'lantern':
		speak("Включаю фонарик")
		lantern.spot_attenuation = 16
	
	elif cmd == 'findthings':
		speak("Ищу по запросу")
	
	elif cmd == 'sms':
		speak("Открываю сообщения")
	
	elif cmd == 'houseplan':
		speak("Вот план здания")
	
	elif cmd == 'stop':
		speak("Сворачиваюсь")
		#godot.get_tree().exit()
   
	else:
		print('Команда не распознана, повторите!')
	 
# запуск
r = sr.Recognizer()
m = sr.Microphone(device_index = 0)
 
with m as source:
	r.adjust_for_ambient_noise(source)
 
speak_engine = pyttsx3.init()
 
speak("Вас приветствует ассистент")
speak("Я вас слушаю")

#r.listen_in_background(m, callback)
while True:
	with m as source:
		audio = r.listen(source)
	value = r.recognize_google(audio, language = "ru-RU")
	print("[log]Распознано: {}".format(value))

	for x in opts['alias']:
		cmd = value.replace(x, "").strip()
		   
	for x in opts['tbr']:
		cmd = value.replace(x, "").strip()
		
	cmd = recognize_cmd(value)
	execute_cmd(cmd['cmd'])
	a = int(input())
`
And some nodes:
Node
   MeshInstance (The ground)
   KinematicBody
        CollisionShape (Capsule form)
        Camera 
        MeshInstance (Player body)
And that's all. Of cource I've installed your addon and libraries for python.

**Comment by HalfL1fe3** [comment]
damn, there are comments, but github recognised them not correctly)

**Comment by HalfL1fe3** [comment]
@touilleMan, I've fixed this error, now everything's ok (I just forgot about installing PyAudio :) ). Now can you say me, how to use singletones? I want to change variables from singletone in my .py script. It should look like that:
`variable = singletone
variable.singletone_variable = value`
If it's possible, of course.

**Comment by HalfL1fe3** [comment]
@touilleMan, I've fixed this error, now everything's ok (I just forgot about installing PyAudio :) ). Now can you say me, how to use singletones? I want to change variables from singletone in my .py script. It should look like that:
```
variable = singletone 
variable.singletone_variable = value
```
If it's possible, of course.
