### ISSUE TITLE
How to include a python file not at the root res://?

### ISSUE THREAD

**Issue by whogben** [touilleMan/godot-python#230]
I'm trying to mix some pure-python files in with my node-subclasses in python, but Godot can't find them unless they're located at the root of res://

Any tips on how to accomplish this?

import Bot from Bot <- works when Bot.py is at the root of Res://, but not when Bot.py is in the same folder as the python node file that's trying to import it.

**Comment by HalfL1fe3** [comment]
I guess that godot doesn't work with files that are located not in res://, but you can try to print the full path

**Comment by whogben** [comment]
> I guess that godot doesn't work with files that are located not in res://, but you can try to print the full path

I'm just trying to include files that are inside sub folders of res://, 

Eg res://pyfile.py can be accessed from a Godot python node with "import PyClass from PyClass"

How can I include res://scriptsfolder/PyClass.py?

**Comment by cridenour** [comment]
Just use standard Python relative imports. Also make sure your folders are actual packages with `__init__.py`

**Comment by thetoblin** [comment]
To be able to import python libraries, it seems to work to add a path to where the python libraries are on disk in the `Project Settings> General> Filesystem> Python Script> Path` using the Godot editor.

I'm using conda, and I've added 
`/home/[username]/anaconda3/lib/python3.8;`
`/home/[username]/anaconda3/lib/python3.8/lib-dynload;/home/[username]/anaconda3/lib/python3.8/site-packages`

which seems to make packages such as math, numpy, etc importable in Godot.

**Comment by cridenour** [comment]
@thetoblin That will make the game unable to be exported / shared. If that's not important to your use case, then no worries!

**Comment by thetoblin** [comment]
@cridenour thanks for the information! Well, it is important to my use case. But for the moment it is worth simply getting the module to work so that I can evaluate whether it is worth spending time on. If it works as intended, I'll fix the problem later =).
