### ISSUE TITLE
Python doesn't seem to work with my Mono? Core API hash Mismatch error.

### ISSUE THREAD

**Issue by LynnCelest** [touilleMan/godot-python#232]
As soon as I installed python, I created a new script in my folder. Then I tried running the game and this error happened: 

E 0:00:22.885   _init_godot_api_hashes: Mono: Core API hash mismatch.
  <C++ Source>  modules/mono/mono_gd/gd_mono.cpp:494 @ _init_godot_api_hashes()

I want to use python for a social sim game I'm making since Nltk has function calls to traverse the latest En-Word.Net (it's an actual website) and along with the other NLP functions. I would prefer an updated hand written wordnet source over machine generated ones. This error doesn't let me use python to even try Nltk out for my needs at all though.

**Comment by touilleMan** [comment]
Hi @LynnCelest !

I never tried to run both mono and Python in the same Godot (though they shouldn't step on each other toe in theory, just like you have gdscript and visualscript running along Python in the non-mono Godot)

Are you sure you don't get this mono error when Python is disabled ?

And can you provide more information about you setup (OS version, 32/64bits, version of Godot, version of Godot-Python) and a bigger stacktrace (typically what commands you run to get the crash and ideally a minimal project producing the crash)

**Comment by LynnCelest** [comment]
Hello @touilleMan! :) I'm 100 percent sure the error doesn't happen when Python is disabled in the GDNative project settings. There was a recent update in Godot that actually addressed this exact problem for Pythonless Godot 3.2. Perhaps the update affected Python Godot if the bug wasn't always possible. Here are the links addressing this bug/update:

https://github.com/godotengine/godot/issues/14584
https://github.com/godotengine/godot/issues/35290
https://godotengine.org/article/release-candidate-godot-3-2-rc-2
https://github.com/godotengine/godot/pull/35326

My set up is Windows 64 bit, Godot 3.2.2.Stable.Mono, and the Python Version on the command prompt says "Pythonscript 0.40.0 (CPython 3.8.3.final.0)"

To reproduce the error on my machine in a minimum project I just: 1. Created a new project. 2. Created a 3D Spatial Node with an empty C# Script. 3. Downloaded and Installed the same version of the Python Add-on 0.40.0 from the AssetLib. At this point running the game would reproduce the API_Hash error but the game wouldn't crash like it would on my main project. Perhaps it's because there is no code? I'm not sure.

4. I restarted godot. 5. I created a python script. The game runs the same. The error comes up but it doesn't crash the game. On my main game the project crashes right after the game window opens up. My main game works fine when I disable the Python Add on though.

Thanks for the response!!!

**Comment by LynnCelest** [comment]
Hey I've been trying to reproduce the crash. I haven't been successful but I'm getting a lot of errors...First off there is this error:

> ERROR: get_breakpoints: Condition "base.begins_with("local://") || base == """ is true. Continuing.
>    At: editor/plugins/script_editor_plugin.cpp:1559
> Running: C:\Users\...path to engine...\Godot_v3.2.2-stable_mono_win64\Godot_v3.2.2-stable_mono_win64.exe --path C:/Users/...path to game.../TestPython --remote-debug 127.0.0.1:6007 --allow_focus_steal_pid 13900 --position 171,84

I don't remember getting this one on my main game but I have to double check. C# runs fine when I try to use GetNode() and print things in this test game. (Despite the API Hash Error.)

For the next error, I tried doing this code: (It's simplified)
```
from nltk import * 
  class WordNet(Node)
    def _ready(self):
       print(corpus)
```
I saved it but when I ran the test game what I wrote got deleted (the script reset to default.) That's when all of these 2k+ errors on this screenshot popped up: ![image](https://user-images.githubusercontent.com/34824025/93008278-dd6f6a80-f540-11ea-9c6e-dc9e07b40447.png) (I'm not sure how to get you the whole 2K+ list yet.)

Then I wrote print() again and now print is giving an error saying "expected indented block" even though it's indented. (This didn't happen the first time I wrote print before my script reset when after running the game despite saving the script.)

I'm also having a third error since when I opened the python script: 
```
from godot import exposed, export
from godot import *
```
Hovering over godot there reads:
> Unresolved Import Godot

Those are 3 errors I'm getting aside from the API_Hash error. Idk if they're unrelated or not. C# seems to be working fine, game didn't crash when the script reset before the 2k+ errors, I don't think python was ever working but idk how to use it.

I just tried running the game again with out the print (It says that even the pass needs to indent?) The game ran fine but it said 

> Cannot load res://NLP/WordNet.py (NLP.WordNet) because it doesn't expose any class to Godot
(This is my test python script. After this next run the indent error went away but the 2K+ VSCode errors didn't.)

I just remembered one more detail about my main game. It would crash when the window loads but some times it would white screen crash on godot before the game window opens too. That's all! I'm having trouble reproducing the crash or running anything on Python x: but it crashes on my main game.

**Comment by LynnCelest** [comment]
Ok so both C# and Python are printing things just fine in the test game.... I am unsuccessful in crashing the test game. The test game is buried in errors despite running and printing. My main game unlike the test game doesn't work at all when the Python Add On is turned on.

**Comment by LynnCelest** [comment]
Hello @touilleMan, This error is unique to my Main Game: 

> AttributeError: module 'godot' has no attribute 'globals'
> Exception ignored in: '_godot.pythonscript_add_global_constant'
> AttributeError: module 'godot' has no attribute 'globals'

Perhaps this is the reason why it crashes?

**Comment by touilleMan** [comment]
Good catch @LynnCelest ! The code handling global constant in python was falty (see #245) ^^
