### ISSUE TITLE
Trying to do simple hello world

### ISSUE THREAD

**Issue by keenfoong** [touilleMan/godot-python#234]
Hi, I'm attempting to do a simple hello world but it doesn't appear for me. Maybe its something simple that I'm missing out out but it's not printing it out for me.

The code

```
from godot import exposed, export
from godot import *

@exposed
class Node2D(Node2D):

	# member variables here, example:
	a = export(int)
	b = export(str, default='foo')

	def _ready(self):
		"""
		Called every time the node is added to the scene.
		Initialization here.
		"""
		print("hello world")
		
```

The output:

``` 
editor/plugins/script_editor_plugin.cpp:1559 - Condition "base.begins_with("local://") || base == """ is true. Continuing.
--- Debugging process started ---
Godot Engine v3.2.2.stable.mono.official - https://godotengine.org
OpenGL ES 3.0 Renderer: GeForce RTX 2080 Ti/PCIe/SSE2
 
Pythonscript 0.40.0 (CPython 3.8.3.final.0)
Calling wrapper on <class 'Node2D.Node2D'>
```

**Comment by keenfoong** [comment]
Hi it turns out it doesn't show within Godot like the screenshot in the [readme](https://raw.githubusercontent.com/touilleMan/godot-python/master/misc/showcase.png). It only appears in the console.

**Comment by touilleMan** [comment]
Yeah, a lot of improvement has been done on the stdout/console output lately, next release will solve this ;-)

**Comment by keenfoong** [comment]
ok great
