### ISSUE TITLE
Accessing built in functions

### ISSUE THREAD

**Issue by keenfoong** [touilleMan/godot-python#235]
Hi how do I access godot's built-in functions?

eg
[https://docs.godotengine.org/en/stable/classes/class_@gdscript.html](https://docs.godotengine.org/en/stable/classes/class_@gdscript.html)

It's not in godot.builtins that I can see.

**Comment by touilleMan** [comment]
Hi @keenfoong !

Builtins functions are not available from Python given they are not exposed by the GDNative api
Is there something in particular you try to achieve with these ?

**Comment by keenfoong** [comment]
At that point I was interested in preload() in particular since it's used in many tutorials. Also maybe lerp.

**Comment by touilleMan** [comment]
there is no use for `preload` in Python given you can execute any code in the global scope of your module, see for here for instance:
https://github.com/touilleMan/godot-python/blob/aa57d43f6a78ef55fda635e3b608727aff71c79a/addons/pythonscript_repl/plugin.py#L1-L12
