### ISSUE TITLE
Python module import error: OSError: Could not load shared object file: libllvmlite.so

### ISSUE THREAD

**Issue by thetoblin** [touilleMan/godot-python#239]
I'm not sure this is where I should post this, but I could think of no other place. Feel free to forgive my ignorance and improve my conduct =).

I'm trying to import a python package called `numba`. But as can be see from the following thread I'm having difficulties doing so: https://github.com/touilleMan/godot-python/issues/238

I'm making an attempt to now copy paste the python packages directly into the main project folder of my Godot project. As `numba` relies on a package called `llvmlite`, I have also copied `llvmlite` into the project folder.

When trying to import `numba` this way however, the code seems to be unable to identify the `libllvmlite.so` file that it is looking for, even though it is in the correct place in the OS file system but appears to be missing in the Godot Editor filesystem.

![libllvmlite](https://user-images.githubusercontent.com/61850783/94609527-34927080-029f-11eb-9b53-00bca5ce1a95.png) ![libllvmlite_missing](https://user-images.githubusercontent.com/61850783/94609662-660b3c00-029f-11eb-8400-7588bc401cd5.png)

My inexperienced mind tells me that there is a problem here with godot-python being able to recognize a `.so` file that has been copy pasted into its OS directory. Does anyone have any ideas?

**Comment by touilleMan** [comment]
I guess you're installing numba wrong:
```
$ cd godot-python/examples/pong/addons/pythonscript/
$ ./x11-64/bin/python3 -m pip install numba
Collecting numba
  Downloading numba-0.51.2-cp38-cp38-manylinux2014_x86_64.whl (3.1 MB)
     |████████████████████████████████| 3.1 MB 7.6 MB/s 
Collecting llvmlite<0.35,>=0.34.0.dev0
  Downloading llvmlite-0.34.0-cp38-cp38-manylinux2010_x86_64.whl (24.6 MB)
     |████████████████████████████████| 24.6 MB 18.9 MB/s 
Requirement already satisfied: setuptools in ./x11-64/lib/python3.8/site-packages (from numba) (47.1.0)
Collecting numpy>=1.15
  Downloading numpy-1.19.2-cp38-cp38-manylinux2010_x86_64.whl (14.5 MB)
     |████████████████████████████████| 14.5 MB 139 kB/s 
Installing collected packages: llvmlite, numpy, numba
Successfully installed llvmlite-0.34.0 numba-0.51.2 numpy-1.19.2
WARNING: You are using pip version 20.1.1; however, version 20.2.3 is available.
You should consider upgrading via the '/home/emmanuel/projects/godot-python-3/build/dist/addons/pythonscript/x11-64/bin/python3 -m pip install --upgrade pip' command.
$ ./x11-64/bin/python3 
Python 3.8.5 (default, Aug 23 2020, 01:02:51) 
[Clang 10.0.1 ] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numba
num>>> numba
<module 'numba' from '/home/emmanuel/projects/godot-python-3/build/dist/addons/pythonscript/x11-64/lib/python3.8/site-packages/numba/__init__.py'>
>>>                                                                                                                                  >>>                                                                                                                                                 >>>                                                                                                                                  >>>                                                                                                                                                 >>> 
>>> from numba import jit
>>> import random
>>> 
>>> @jit(nopython=True)
... def monte_carlo_pi(nsamples):
...     acc = 0
...     for i in range(nsamples):
...         x = random.random()
...         y = random.random()
...         if (x ** 2 + y ** 2) < 1.0:
...             acc += 1
...     return 4.0 * acc / nsamples
... 
>>> monte_carlo_pi(42)
3.238095238095238
>>> 
```

To install the dependencies the right way you must use the pip provided by the godot-python project (doing `./x11-64/bin/pip` is broken, you must use `./x11-64/bin/python3 -m pip` !)

**Comment by thetoblin** [comment]
Thanks as always for your replies =)

Trying to install numba using your proposal leads to:
```
tobka@lindstrom:~/python_godot_3/addons/pythonscript$ ./x11-64/bin/python3 -m pip install numba
/home/tobka/python_godot_3/addons/pythonscript/x11-64/bin/python3: No module named pip
```
Does this have to do with godot-python, or is it a system problem?

**Comment by touilleMan** [comment]
Ha ! try doing this before using pip:
```
$ ./x11-64/bin/python3 -m ensurepip
```

**Comment by thetoblin** [comment]
> $ ./x11-64/bin/python3 -m ensurepip

Did the trick! Numba was installed using pip. I'll proceed to trying to use the package in Godot-python =)
