### ISSUE TITLE
Godot language support 

### ISSUE THREAD

**Issue by ShalokShalom** [touilleMan/godot-python#241]
Hi 😄 

[Our little project](https://github.com/Vivraan/godot-lang-support) maintains a list of all the supported languages in Godot and is embedded in the Discord bot with the !lang command.

Please take a look, if you can and will contribute, by providing additional information and insight into the project; here are some points who are particularly important in my view:

Which editors support your binding, and how?
Which platforms are known to work, which one have you tested and which ones are targeted?

You might wanna share your ideas here, thanks a lot:
https://github.com/Vivraan/godot-lang-support/issues/26

🥳

**Comment by touilleMan** [comment]
Hi @ShalokShalom !

Your godot-lang-support seems a good idea, I've answered your question here https://github.com/Vivraan/godot-lang-support/issues/26#issuecomment-703107965
