### ISSUE TITLE
Coconut

### ISSUE THREAD

**Issue by ShalokShalom** [touilleMan/godot-python#243]
Hi! I was wondering how you think about a superset of Python, that adds many new, exciting features to it, it is actively maintained by a former Google, OpenAI and Yelp employee and I would love to have it in Godot:

"Coconut is a variant of Python built for simple, elegant, Pythonic functional programming. Coconut syntax is a strict superset of Python 3 syntax. Thus, users familiar with Python will already be familiar with most of Coconut."

   ```
    pipeline-style programming
    pattern-matching
    algebraic data types
    destructuring assignment
    partial application
    lazy lists
    function composition
    prettier lambdas
    infix notation
    operator functions
    tail call optimization
    where statements
```

**Comment by touilleMan** [comment]
Hi @ShalokShalom ,

Given Coconut compiles to Python, the simplest way to use Coconut in Godot would be to run a script doing the compilation before running Godot.
Typically using the `coconut --watch` option that automatically recompile when a file changes.

**Comment by ShalokShalom** [comment]
Yeah, support in the editor would be superb.
