### ISSUE TITLE
Self.clamp() function showing 'player' object has not attribute 'clamp'

### ISSUE THREAD

**Issue by Harshharsh2275** [touilleMan/godot-python#248]
When using clamp function in my 2d node script like self.clamp() showing error clamp is not a attribute of 'player' class

**Comment by touilleMan** [comment]
Hi @Harshharsh2275 !

It seems `clamp` is not a method but a GDScript builtin method (just like `sin` or `print`), so it's not currently available from the Python binding.
However you should be able to implement the clamp in python by doing:
```python
def clamp(value, min_value, max_value):
    return max(min_value, min(max_value, value))
```

**Comment by Harshharsh2275** [comment]
> Hi @Harshharsh2275 !
> 
> It seems `clamp` is not a method but a GDScript builtin method (just like `sin` or `print`), so it's not currently available from the Python binding.
> However you should be able to implement the clamp in python by doing:
> ```python
> def clamp(value, min_value, max_value):
>     return max(min_value, min(max_value, value))
> ```

Actually I accomplished my task another way but it's fine.
