### ISSUE TITLE
How to convert python nested list to Godot?

### ISSUE THREAD

**Issue by thetoblin** [touilleMan/godot-python#252]
If I have a nested list `nested = [[1,2,3],[4,5,6]]`, how do I convert it from python to Godot? 

Converting an ordinary list `normal = [1,2,3,4,5,6]` is no problem by using `godot.Array( normal )`. But how do I convert a nested list?

I'm guessing that it's not possible at the moment, so I'm more or less trying to confirm that I have to create my own conversion script =).

**Comment by touilleMan** [comment]
Hi @thetoblin !

Yep, there is currently no automatic conversion between nested python list and nested `godot.Array`
However you can simply do the conversion:
```python
gd_nested = godot.Array([godot.Array(py_sublist) for py_sublist in py_nested])
```
