### ISSUE TITLE
error(-1,0) after fresh install on Win10 in Godot 3.2.3stable

### ISSUE THREAD

**Issue by andreas-paul** [touilleMan/godot-python#255]
Hi there,

I'm trying to make python work in Godot 3.2.3stable. After having installed the package from the Assetlib and restarted Godot, I can attach Python scripts to nodes alright. However, even with the default script only, no changes made, I receive an error message 'error(-1,0) at the bottom of the script window, related to the import on the 1st line (`from godot import exposed, export`). If I run a node with the starter script attached, nothing is happening: 

```
--- Debugging process started ---
--- Debugging process stopped ---
```

Running python from the command line works fine. I'm on Win10 btw. Are there any solutions available? Followed what little guidance is available, to no avail.

**Comment by gustavi** [comment]
Hello. I have the `error(-1,0)` but this is only on the editor and not related to content I guess.

You should try the last version which works fine with Godot 3.2.3 : https://github.com/touilleMan/godot-python/releases/tag/v0.50.0

If no change, can you paste your code ?

**Comment by touilleMan** [comment]
besides the new version 0.50.0 is also finally on the asset store: https://godotengine.org/asset-library/asset/179

**Comment by andreas-paul** [comment]
Thank you guys! It seemed it was the old version that made trouble. After having downloaded the Python add-on through the asset-lib and restarted Godot, it works now. The error is still there though.
