### ISSUE TITLE
Windows project compile error

### ISSUE THREAD

**Issue by batkins2** [touilleMan/godot-python#256]
```Godot Engine v3.2.3.stable.official - https://godotengine.org
OpenGL ES 3.0 Renderer: GeForce GTX 1080 Ti/PCIe/SSE2

ERROR: Can't open dynamic library: addons/pythonscript/windows-64/pythonscript.dll, error: Error 126: The specified module could not be found.
.
   At: platform/windows/os_windows.cpp:2395
ERROR: No loader found for resource: res://Game.py.
   At: core/io/resource_loader.cpp:286
ERROR: poll: res://World.tscn:4 - Parse Error: [ext_resource] referenced nonexistent resource at: res://Game.py
   At: scene/resources/resource_format_text.cpp:440
ERROR: Failed to load resource 'res://World.tscn'.
   At: core/io/resource_loader.cpp:208
ERROR: Failed loading resource: res://World.tscn. Make sure resources have been imported by opening the project in the editor at least once.
   At: core/io/resource_loader.cpp:278
ERROR: Failed loading scene: res://World.tscn
   At: main/main.cpp:1944
WARNING: cleanup: ObjectDB instances leaked at exit (run with --verbose for details).
     At: core/object.cpp:2135
ERROR: clear: Resources still in use at exit (run with --verbose for details).
   At: core/resource.cpp:477

**Comment by touilleMan** [comment]
Hi @batkins2 !

What version of Godot-Python are you using (version 0.50.0 has been released a couple of days ago, can you try with this version ?)
Can you provide the command you typed as well as the project layout ? (typically from which directory are you running Godot)

**Comment by touilleMan** [comment]
btw from the title of this issue I guess you are building the project by yourself (hence not using the release from the asset lib or the github release page). If that's the case, how did you have installed the resulting built into your own project ?

**Comment by batkins2** [comment]
I downloaded the project into an existing project using the asset library, v0.50.0, and exported to win64 exe. The path to the dll seems correct but should it be prefixed with res://?

**Comment by touilleMan** [comment]
Export is not yet supported, so you end up with an exported project missing the dll ;-)

**Comment by Folcon** [comment]
Is this still a problem?
I did a test and got:
```
```
