### ISSUE TITLE
will there be a python 3.9.X update

### ISSUE THREAD

**Issue by UnknownS1024** [touilleMan/godot-python#257]
not surprisingly v0.40.0 and v0.50.0 not updated to 3.9 why :)) by the way python 3.9 1 month ago the release was released
![image](https://user-images.githubusercontent.com/17591539/100498020-4e9de180-3170-11eb-85b5-baa5d071a611.png)

**Comment by Madaraz1024** [comment]
python 3.9 much faster performance :+1:

**Comment by touilleMan** [comment]
Hi @Madaraz1024,

Python 3.9 will most likely be shipped on the next release (most likely meaning except if it introduce an unexpected incompatibility 😄 )

If you want to help, you can provide a PR which modifies the `platforms/xxx/SConscript` (see https://github.com/touilleMan/godot-python/blob/master/platforms/x11-64/SConscript for instance) to add the support for 3.9
