### ISSUE TITLE
I'm not sure if it worked exporting X11 platform game

### ISSUE THREAD

**Issue by Madaraz1024** [touilleMan/godot-python#258]
linux opensuse / official godot 3.2.3 / python 3.8.6

build х11 run game result error not found file libpythonscript.so file is already nearby
![image](https://user-images.githubusercontent.com/17591539/100497677-24e3bb00-316e-11eb-9f91-3dac3ac5372c.png)

![image](https://user-images.githubusercontent.com/17591539/100497850-0f22c580-316f-11eb-91f2-87208abae857.png)

![image](https://user-images.githubusercontent.com/17591539/100497700-404ec600-316e-11eb-902e-71a6ab089907.png)
this is very strange the export of the platform is almost dead

godot-python editor just perfect only problem exporting platform not working :)

**Comment by Madaraz1024** [comment]
very little info python README description want youtube tutorial to explain to all users to understand build python (win, x11, macos) :+1:

**Comment by gustavi** [comment]
Please read the [README FAQ](https://github.com/touilleMan/godot-python#faq).

**Comment by Madaraz1024** [comment]
[README FAQ](https://github.com/touilleMan/godot-python#faq) it looks like old info godot 3.0 needs to be corrected new (cause scons version changed very much)

1) requirements.txt  error

![image](https://user-images.githubusercontent.com/17591539/100498335-932a7c80-3172-11eb-8a14-61d320599ea5.png)

2) `scons platform=x11 target=release_debug bits=64 or bits=32`

![image](https://user-images.githubusercontent.com/17591539/100498383-dd136280-3172-11eb-92b9-3610d3d8f6d9.png)

![image](https://user-images.githubusercontent.com/17591539/100498405-fd432180-3172-11eb-8f25-b5d862549c2e.png)

**Comment by gustavi** [comment]
https://github.com/touilleMan/godot-python/issues/146

**Comment by gustavi** [comment]
Export system is not available yet https://github.com/touilleMan/godot-python/issues/146

**Comment by Madaraz1024** [comment]
I have already read the results nothing good will bring an error there description short pleasures still unclear time to spend a lot already said README need more about new python-godot extension info

ok the topic can be closed anyway users still don’t understand short description of README and don’t use godot-python a lot of problems don’t want longer prototype of the game will be abandoned.

**Comment by gustavi** [comment]
I understand you are not English native speaker (me neither) but use punctuation on your sentences. I don't understand at all what you said :/

**Comment by Madaraz1024** [comment]
@gustavi sorry, bad english

**Comment by gustavi** [comment]
I still don't understand but OK. FYI I'm currently developing a game with Godot-Python and it works well. I have almost 10k lines of code working perfectly.
