### ISSUE TITLE
Tool python script

### ISSUE THREAD

**Issue by romantolkachyov** [touilleMan/godot-python#259]
Is it possible to implement something like `tool` keyword in GDScript? Looking for a way to render my generated mesh in editor.

**Comment by touilleMan** [comment]
Hi @romantolkachyov,

Yes, `tool` is supported. As a matter of fact the python-repl plugin is itself written in Python so you can use it as an example: https://github.com/touilleMan/godot-python/blob/6b2225c00bd31b0108b6785532cef38a5a64534e/addons/pythonscript_repl/plugin.py#L8

**Comment by romantolkachyov** [comment]
Thanks! It would be great to add it to the documentation.
