### ISSUE TITLE
How to call autoloaded scripts?

### ISSUE THREAD

**Issue by Codified-Vexing** [touilleMan/godot-python#260]
I have a node's python script trying to refer to a method in python singleton. It throws an AtributeError: 'this_node' object has no attribute 'settings'

**Comment by touilleMan** [comment]
Hi @Codified-Vexing,

When mixing Python and Godot, you endup with two possible views of a Python node:
- you got the node from pure Python code (for instance your stored the node in a global variable during it initialization in Python
- you got the node from the Godot API (typically what you endup with when using `self.get_node(...)`)

So most of the time you have code executed in a Python node (so this node is view as the correct Python class when using `self`) but when dealing with other nodes you have first to retrieve them (so going through Godot API) which means you'll get a 

For instance if you declare a `class Player(KinematicBody2D)` you'll correctly have `type(self) == Player` when inside one of it methods, but if you retrieve the node from the Godot API you'll get a `KinematicBody2D` (the Python stuff being attached as a script, this is the same behavior than if you implement Player in GDScript by the way).

You can still access the script attributes and methods from `KinematicBody2D`, however those fields must be explicitly defined:
- methods are automatically exported so nothing to do here ;-)
- attributes must use the `@export` decorator (so my guess is you are trying to access a field that is not exported)

**Comment by Codified-Vexing** [comment]
I don't fully understand.
Let's say I have a node in a tree attached to a python script, Foo.py. And I want to press a button to get an attribute "num" in a singleton called "Glob".
The following won't work:
```py
# In Foo.py
def _on_button_pressed(self):
    print( Glob.num )
```
```py
# In Glob.py
@exposed
class Glob(Node):
    num = 42
```

How can I make it print `42`?

**Comment by touilleMan** [comment]
```python
@exposed
class Glob(Node):
    num1 = 42  # This declares a class attribute, Godot has no information about it
    def __init__(self):
       self.num2 = 42  # This is a the pythonic way to declare a class instance attribute, however there is no infomation about this when class is defined so we cannot tell Godot about this

        num3 = export(int, default=42)  # This is the correct way to declare a class intance attribute accessible from Godot
```

**Comment by Codified-Vexing** [comment]
Aaaah Thank you. Do we have to always tell the datatype in `export()`, can't we have a duck typed variable?

**Comment by touilleMan** [comment]
>  can't we have a duck typed variable?

No sorry, all exposed attribute must be defined when the class is defined (including methods, so you cannot do something like `foo = Foo(); foo.bar = lambda: 42` to dynamically add a method and expect it to be visible from Godot)

>  Also, is there another way to access the autoloaded scripts. Other way than self.get_node("/root/Glob")

You can store the node in a python global variable and access it from there:
```python

# in my_node.py
my_node = None

@exposed
class MyNode(Node):
    def _ready(self):
        global my_node
        my_node = self

        self.foo = 42

# in another_node.py

from my_node import my_node

class MyNode(Node):
    def _ready(self):
        assert my_node.foo == 42

```
