### ISSUE TITLE
make: scons: command not found

### ISSUE THREAD

**Issue by anzhi0708** [touilleMan/godot-python#263]
Hi, I know this might be silly, but I could not run `make` command, it throws me an error `make: scons: command not found`.
I have scons==3.1.1 installed. 
When I run `scons`, it says `/usr/bin/env: “python”: no such file or dictionary`.
I tried to `export python=$(which python3)` but still won't work.
I'm running Linux Mint and have python 3.8.5 installed. BTW I aliased python3 to 'python' in ~/.bashrc.
What did I miss?

**Comment by touilleMan** [comment]
hi @anzhi0708 ,

Funny I didn't even remember the project contained a `Makefile`, I always run the project through `scons` directly ;-)

> OK I just did ln -s /usr/bin/python3 usr/bin/python and now scons gives me a new error:

This is not a good idea (your risk to break your linux installation doing this), you should instead use a virtual env:
```shell
$ python -m venv venv # create a python virtualenv named "venv" within your current directory
$ . ./venv/bin/activate  # enable the virtualenv
$ pip install scons==3.1.1  # install scons within the virtualenv
$ which scons
<my_path>/venv/bin/scons
```
