### ISSUE TITLE
Export Script Variables to show in Editor

### ISSUE THREAD

**Issue by Codified-Vexing** [touilleMan/godot-python#264]
In GDScript you can make a variable modifiable in the Editor by using the "export" keyword.
How can I have these script variables with Python?

**Comment by GamesOpenSource** [comment]
From `examples/pong/paddle.py`:
```
    left = export(bool, default=False)
    action_prefix = export(str, default="")
    can_move = export(bool, default=False)
```

Trying to figure out how to do this for an AudioStreamPlayer. If you have any idea, please share.

**Comment by Codified-Vexing** [comment]
I thought that only made the attributes available to be called in other Godot scripts. Somehow it isn't working for my intended purpose. Could it be because my python scripts don't run in the Editor at all? They are always triggering error at line (-1,0) without stating the error it is.
