### ISSUE TITLE
How to export a node/NodePath

### ISSUE THREAD

**Issue by GamesOpenSource** [touilleMan/godot-python#268]
Hi, like Unity has public GameObjects, I'd like to export a node to allow me to drag & drop onto the var.

Is this possible?

```
	left = export(bool, default=False)
	action_prefix = export(str, default="")
	can_move = export(bool, default=False)
```

Above code works - taken from the pong example.

But how would I translate the following gdscript to PythonScript, if possible?

```export(NodePath) var nodeymcnodeface;```

None of these work:

```
        nodeymcnodeface = export(node, default=False)
        nodeymcnodeface = export(Node, default=False)
        nodeymcnodeface = export(nodepath, default=False)
        nodeymcnodeface = export(NodePath, default=False
```

**Comment by GamesOpenSource** [comment]
OK, got it.

1. improt `NodePath`. For example,
```from godot import exposed, signal, export, Node2D```
becomes
```from godot import exposed, signal, export, Node2D, NodePath```

2. use `NodePath`
```nodeymcnodeface = export(NodePath)```

3. If the inspector doesn't show the exported variable, save and restart Godot

**Comment by gamepad-coder** [comment]
> If the inspector doesn't show the exported variable, save and restart Godot

I've been trying to resolve this for hours, thanks!
Until just now, I thought it was an issue with the addon install.

I wasn't seeing the default script template variable exports appearing in the Inspector Dock until I tried restarting Godot (or restarting the Scene's tab). That did the trick!

In case anyone else stumbles across this:
- Closing the scene's tab and re-opening the scene  
also updates `Script Variables` in the Inspector Dock. Do this if you add new `export()`ed variables.
- Switching to a different node in the Scene Dock then back to the node with your Python script will refresh any exported strings from the script. Do this if you update an existing `export()`'s defaults.
- 
![2022-11-20 17_40_35-](https://user-images.githubusercontent.com/65138515/202932927-e3f1c076-6cc3-486d-b7fb-8c2c75cfb4f6.png)

<br><br><br>

--------------
<kbd>
<br>Using
<br>- Godot 3.5.1 
<br>- godot-python [v0.50.0] Nov 15, 2020 -- installed from the asset store.
<br>- Windows 10
</kbd>

**Comment by gamepad-coder** [comment]
Addendum:

If anyone sees an error like
```
Another resource is loaded from path 'res://test/ControlToTest.py' (possible cyclic resource inclusion).
```
It's a side effect of using an external editor with this `godot-python` add-on.
Other related topics make it seem like it's an issue with multiple threads accessing the same resource.
