### ISSUE TITLE
Accessing export variable of type Material causes SigSegV (11).

### ISSUE THREAD

**Issue by ans3pl** [touilleMan/godot-python#270]
```
var mat = export(ShaderMaterial)
print(dir(mat))
```
will cause crash with code 11 but
```
var mat = ShaderMaterial()
print(dir(mat))
```
wont cause game to crash

I wonder if this has something to do with type being refcounted ( refcounted use constructor, not refcounted .new() )

**Comment by touilleMan** [comment]
Hi @ans3pl (and sorry for the delay ^^)

`export(ShaderMaterial)` should be only used when declaring a class, it doesn't instantiate a `ShaderMaterial`

However this shouldn only cause a python exception, not a segfault !

I've tried on my side but couldn't reproduce the crash with:

```python
def test_invalid_export_use():
    from godot import export, ShaderMaterial
    mat = export(ShaderMaterial)
    print(dir(mat))
```

I'm not sure about your example, you use `var mat = ...` which indicate you use GDScript (but then your example would have nothing to do with Godot-Python !), on the other hand `dir(mat)` is not available in GDScript as far as I know...

Can you improve your example and provide the version of Godot/Godot-Python and your OS ?

**Comment by dranorter** [comment]
For the record, I tried as many variations as I could think of and was unable to reproduce this crash.

**Comment by touilleMan** [comment]
thanks @dranorter ;-)
