### ISSUE TITLE
No Python Option While Creating Scripts

### ISSUE THREAD

**Issue by CodeDecodeDev** [touilleMan/godot-python#272]
Hello, I want to use Godot with Python. I found out about this package and installed it but I was unable to get it working, can anyone help me? Please tell what all do i need to do. Thanks in advance

**Comment by INdIEDeV016** [comment]
After downloading/installing you need to **Restart The Godot Editor**. After restart, when you will attempt to create a new script, (e.g when you are attaching a script to a node or creating a new script file from the file system dock) you will get the option to create a new Python Script.
