### ISSUE TITLE
what is error(-1, 70498496)?

### ISSUE THREAD

**Issue by P0PCAT-012345** [touilleMan/godot-python#277]
![image](https://user-images.githubusercontent.com/80101058/110104744-e4d64900-7dea-11eb-872a-33894540f0ae.png)
Every single time I attach a new godot-python file, this error message pops up.
Not only that, putting print() or other functions in def _ready or def _process(delta) doesn't work
is there any way to fix this?

**Comment by vmjcv** [comment]
I will also pop up an error message, but the game can run normally

**Comment by dranorter** [comment]
Hi there, I don't know where the large numbers come from, but essentially the Godot script editor does not really understand the Python files. It's trying to find syntax errors before you run anything, the way it would in GDScript, but this sort of check has not been implemented for Python so it fails. It would be cleaner looking to suppress this error, but it doesn't affect how anything runs.
