### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by bhkeys** [touilleMan/godot-python#28]
So you say that the build only works on Linux at the moment
But say if I make a demo in Linux, can I still export to the other OS's that Godot exports to?

Also, if I include external python modules; how does that effect making the project export-able to all platforms?

Is debugging included in the workflow?

**Comment by touilleMan** [comment]
In Godot, exporting basically means putting your project folder along with a Godot release build for the target platform.

Given for the moment there is no Godot build containing Python for other platforms than Linux, your project won't work on other platforms (it will complains it cannot load the .py files)

> Is debugging included in the workflow?

You can put `pdb.set_trace()` anywhere in your python code, so far you have to control the debugging through the terminal that have launched your godot program (unlike with gdscrit which prints to the internal godot editor console). This is part of the features to improve before having a nice windows build (people don't start there program from a terminal on Windows ^^).
