### ISSUE TITLE
Using variable from python to GDscript outside

### ISSUE THREAD

**Issue by P0PCAT-012345** [touilleMan/godot-python#282]
I had a problem trying to importing and exporting variables between GDscript and python.

```python
@exposed
class autoload(Node):
	def __init__(self):
	
		self.var1 = 1
		var2 = export(int, default = 2)
		return var2
```
if I had a python script like this,

```gdscript
var PingPongAi = get_node("/root/PingPongAi")
print(PingPongAi.autoload())
```
and GDscipt like this, 

I get a error saying:
Invalid call. Nonexistent function 'autoload' in base 'Node (ping_pong_ai.py)'.

How do I fix this?

**Comment by touilleMan** [comment]
Hi @P0PCAT-012345 

It seems you are trying to call `autoload` which is the name of the class, not the name of a method (the class is automatically instantiated when the script file is instantiated, just like in gdscript)
