### ISSUE TITLE
How to fix issue with variable in class 

### ISSUE THREAD

**Issue by P0PCAT-012345** [touilleMan/godot-python#287]
![image](https://user-images.githubusercontent.com/80101058/111897654-9a003680-8a64-11eb-9d5c-29be4cb8e64a.png)
When I do this, I get this error message saying 
" NameError: name 'var' is not defined "
I do I fix this error?

**Comment by touilleMan** [comment]
Scope definition for the two classes are separated
you should use a global helper variable:
```python
_var = 1
@exposed
class autoload(Node):
    var = _var
    class this:
        var2 = _var
del _var  # Not needed, but just to cleanup the module scope
```
