### ISSUE TITLE
struggle to download the pyproj  library

### ISSUE THREAD

**Issue by giamo152** [touilleMan/godot-python#289]
Hi,
I am trying to add the pyproj library but I get this error. Anyone knows how to deal with it?

![Screenshot](https://user-images.githubusercontent.com/43810699/114039399-fd6ece80-9882-11eb-98ef-f9affe9044df.png)

**Comment by dranorter** [comment]
It looks like you may be using your system python instead of the godot-specific python; you should be typing `./python -m pip install pyproj`.

**Comment by giamo152** [comment]
Unfortunately such command has never worked for me. Running the python3.8 command was the only way I could see libraries 
actually imported into Godot. It worked fine with numpy, rasterio etc., except this pyproj.
Below is what I get in Godot if I use your command line althouh as you can see (further below) the command in the terminal is successful.

![screenshot](https://user-images.githubusercontent.com/43810699/114135494-98aa8700-9909-11eb-8b18-b71708ed4a8c.png)


![screenshot2](https://user-images.githubusercontent.com/43810699/114135776-09ea3a00-990a-11eb-911a-05c16ebaa304.png)

**Comment by dranorter** [comment]
You need to be in the correct directory for your platform, or use the correct path. For example I typically have my console open to the project directory, and type `./addons/pythonscript/x11-64/python -m pip install`. But if I’m in the x11-64 directory already, then I would just type `./python -m pip install`.

**Comment by giamo152** [comment]
First of all thank you for the support and the patience.
Unfortunately this is what I get when I do as you say.

![image](https://user-images.githubusercontent.com/43810699/114357225-cbef4f00-9b71-11eb-932f-6d9ec1f808d8.png)

Is there something I am missing? Like some permission to enable? Below is the content of the bin file.

![image](https://user-images.githubusercontent.com/43810699/114357153-af531700-9b71-11eb-8412-60d7e7e087a7.png)

**Comment by dranorter** [comment]
Apologies, I was on my Windows environment when I replied, so my description of what to do on Linux wasn't accurate. The correct thing to run is the python3 executable that you see in the /bin folder, so you'd need to either be inside that directory and run ./python3, or of course be somewhere else and give the relative path, such as `./addons/pythonscript/x11-64/bin/python3` from your project directory.

In any case, if it refuses to run at that point you can add the execution permission by running `chmod ug+x python3` while in the `/bin` folder.

And like any fresh godot-python install, you may need to run `./python3 -m ensurepip` before installing packages.

The fact that you've been able to install packages, and then use them inside Godot, in the past, makes me wonder whether we'll get anywhere here, but it at least will mean we're sure it's the right Python environment having the problem.

**Comment by giamo152** [comment]
Thank you so much. It finally works!
For people who are beginners and might have my same issues here is how.
As you can see below, simple ./python3  would take me to the python shell/environment (I don't know!)

![image](https://user-images.githubusercontent.com/43810699/114664033-70e96380-9cfb-11eb-9246-44d318550907.png)

So the original ./python3.8 command has been for me the way to do it. The only difference now is that Thanks to @dranorter I was able to have ensurepip work first. Something I couldn't do originally.
![image](https://user-images.githubusercontent.com/43810699/114664352-dccbcc00-9cfb-11eb-9f5e-31b8bc337c51.png)
