### ISSUE TITLE
It crash and leave this log on the terminal.

### ISSUE THREAD

**Issue by skarmiglione** [touilleMan/godot-python#29]
optirun ./godot.x11.opt.tools.64.llvm
GLES3: max extensions: 317
hdr supported: 1
GLES3: max ubo light: 409
GLES3: max ubo reflections: 455, ubo size: 144
Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
Fatal Python error: Py_Initialize: Unable to get the locale encoding
ModuleNotFoundError: No module named 'encodings'

**Comment by touilleMan** [comment]
Yep this is related to #23, basically you have to manually set `PYTHONHOME` env var before running

example for running the tests:
```
$ cd tests/bindings
$ PYTHONHOME=../../pythonscript/cpython/build/ ../../godot/bin/godot.x11.tools.64.llvm
```

**Comment by touilleMan** [comment]
PYTHONHOME is much better handled now, should no longer be an issue
