### ISSUE TITLE
Autocomplete support

### ISSUE THREAD

**Issue by irfan-hossain-bhuiyan** [touilleMan/godot-python#294]
How can I get autocomplete support for python?

**Comment by touilleMan** [comment]
Hi @irfan-hossain-bhuiyan 

Auto-complete is WIP:
- autocomplete for Python is not yet available within Godot code editor (it should be implemented here https://github.com/touilleMan/godot-python/blob/c3973d9e7965577abe61bb01c70fd49a70e01204/pythonscript/_godot_editor.pxi#L105)
- `.pyi` are provided in (typically in `addons/pythonscript/windows-64/Lib/site-packages/godot/`), you can use that to have autocomplete with external editor (e.g. vscode with the Python plugin)
