### ISSUE TITLE
tcl lib path not found (_tkinter.TclError: Can't find usable init.tcl in the following directories:) 

### ISSUE THREAD

**Issue by chrisgraf** [touilleMan/godot-python#303]
When trying to use tkinter the following happens:
```
 File "<path to godot project>/addons/pythonscript/x11-64/lib/python38.zip/tkinter/__init__.py", line 2261, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: Can't find a usable init.tcl in the following directories: 
    /tools/deps/lib/tcl8.6 ./lib/tcl8.6 ./lib/tcl8.6 ./library ./library ./tcl8.6.10/library ./tcl8.6.10/library
```
`addons/pythonscript/x11-64/lib/tcl8.6` does exist but the working directory seems to be different so it does not get found. Is it possible to change the paths during building godot-python so tkinter works out of the box?

**Comment by touilleMan** [comment]
hi @chrisgraf 

Python interpreter is provided from the [python-build-standalone project](https://github.com/indygreg/python-build-standalone).
There seems to be a guide about your issue on the project's documentation: https://python-build-standalone.readthedocs.io/en/latest/quirks.html?highlight=tcl#tcl-tk-support-files

**Comment by chrisgraf** [comment]
Thanks for that hint!!

**Comment by chrisgraf** [comment]
Just as a reference for somebody trying this for themselves: these 3 lines before any call to a library requiring tcl did it for me:
```
import os
import sys
os.environ["TCL_LIBRARY"] = os.path.join(sys.base_exec_prefix, "lib", "tcl8.6")
```
