### ISSUE TITLE
Invalid type in function 'GetCoordinates' in base 'Node (GetCoord.py)'. Cannot convert argument 2 from Nil to Nil.

### ISSUE THREAD

**Issue by slasken06** [touilleMan/godot-python#310]
When i try to call a function in a python script from gdscript i get that error

![image](https://user-images.githubusercontent.com/56585404/134964663-58eb68d2-44f9-44e4-9f6b-6b77c8d2c311.png)

Any help would be greatly appreciated.

**Comment by slasken06** [comment]
Nvm i solved it.

**Comment by asipes** [comment]
How?

**Comment by AskSkivdal** [comment]
This was a while ago but i am pretty sure i solved it by looking in the output and handeling the python error that shows up there.
