### ISSUE TITLE
Please help a student Makefile:67: recipe for target 'setup' failed

### ISSUE THREAD

**Issue by Ry10p** [touilleMan/godot-python#32]
Hello, 

Looking for a little setup advice.

ln: failed to create symbolic link '/home/ry/GoDOT/GODOT/godot-python/godot/godot': No such file or directory
Makefile:67: recipe for target 'setup' failed
make: *** [setup] Error 1

How do I connect the folder correctly?

Thanks in advance

**Comment by razvanc-r** [comment]
you have to create a symbolic link to godot (and it has to be named exactly `godot`) inside of your godot-python folder, so:

```
cd $GODOT_PYTHON
ln -s $ABSOLUTE_PATH_TO_GODOT godot
```

where `$GODOT_PYTHON` is the folder where you downloaded/cloned the `touilleMan/godot-python` repository and the other variable is you know... self explanatory.

It seems that you liked godot inside of godot-python/godot, it has to be inside of godot-python.

**Comment by Ry10p** [comment]
@razvanc-r 
For some reason no matter what I am running i get that extra gotdot...

ry@X1Carbon:~/G/GODOT-PYTHON/godot-python$ make setup GODOT_TARGET_DIR=/home/ry/G/GODOT-PYTHON/ 
ln -s /home/ry/G/GODOT-PYTHON/ /home/ry/.MyShit/G/GODOT-PYTHON/godot-python/godot/godot
ln: failed to create symbolic link '/home/ry/G/GODOT-PYTHON/godot-python/godot/godot': Not a directory
Makefile:67: recipe for target 'setup' failed
make: *** [setup] Error 1

**Comment by razvanc-r** [comment]
It's difficult to understand what you're doing without knowing where your godot directory is and where godot-python is (absolute paths). Tell me those and I'll give you the command lines to run to set it up properly (without `make setup`)

**Comment by Ry10p** [comment]
There is a
.godot located in the ry@X1Carbon:~/.godot$ 

ry@X1Carbon:~/GDK/Godot_v2.1.4-stable_x11.64

and the 
ry@X1Carbon:~/GDK/godot-python$ This is the one I cloned from github 
with 
git clone --recursive https://github.com/touilleMan/godot-python.git

**Comment by razvanc-r** [comment]
No... I guess you misunderstood how this works. I'll give you the fresh steps from start to finish:

```
cd $HOME
mkdir godot-tmp
cd godot-tmp
git clone https://github.com/godotengine/godot.git
git clone --recursive https://github.com/touilleMan/godot-python.git
# there's a bug in the `Makefile` so `make setup` doesn't work
ln -s $HOME/godot-tmp/godot $HOME/godot-tmp/godot-python/godot
ln -s $HOME/godot-tmp/godot-python/pythonscript $HOME/godot-tmp/godot/modules/pythonscript
make generate_gdnative_cffidefs
make generate_cffi_bindings
make compile
# optional
make tests
make example
```

**Comment by Ry10p** [comment]
@razvanc-r 

When running this command:
ry@X1Carbon:~/godot-tmp/godot-python$ make generate_gdnative_cffidefs

I am getting this error:
/home/ry/godot-tmp/godot-python/tools/generate_gdnative_cffidefs.py --output /home/ry/godot-tmp/godot-python/pythonscript/cffi_bindings/cdef.gen.h /home/ry/godot-tmp/godot-python/godot
cpp: error: /home/ry/godot-tmp/godot-python/godot/modules/gdnative/godot/gdnative.h: No such file or directory
cpp: warning: ‘-x c’ after last input file has no effect
cpp: fatal error: no input files
compilation terminated.
Traceback (most recent call last):
  File "/home/ry/godot-tmp/godot-python/tools/generate_gdnative_cffidefs.py", line 61, in <module>
    fd.write(generate(args.godot_root_path))
  File "/home/ry/godot-tmp/godot-python/tools/generate_gdnative_cffidefs.py", line 47, in generate
    first_line = next(i for i, line in enumerate(splitted_src) if 'godot' in line.lower())
StopIteration
Makefile:117: recipe for target 'generate_gdnative_cffidefs' failed
make: *** [generate_gdnative_cffidefs] Error 1

**Comment by razvanc-r** [comment]
I think there's a bug in that script, might be that gdnative changed places meanwhile, I haven't tried recompiling lately. Given that you have very limited knowledge in compiling & command line, you should just use the release: https://github.com/touilleMan/godot-python/releases/download/v0.9.0/godot-python-0.9.0.tar.bz2 for now at least. There's a readme inside the archive, but basically all you need to do is execute `./run_godot` in the extracted folder.

**Comment by Ry10p** [comment]
@razvanc-r 

Super Cool!

Thank you for taking the time to do that.

**Comment by touilleMan** [comment]
hi @Ry10p !

I suggest you have a look at the [travis builds](https://travis-ci.org/touilleMan/godot-python/branches) in order to know which version of Godot works.
Truth is Godot's GDnative is moving really fast right now, so build breaks often. As a matter of fact I'm currently working on this and hope the build system for godot python will eventually be much easier once GDnative will be mature enough (e.i. once Godot v3.0 is released basically).
