### ISSUE TITLE
Can asyncio be used in godot-python?

### ISSUE THREAD

**Issue by kcfresh53** [touilleMan/godot-python#332]
This project is amazing and I have been able to use different python modules successfully but for modules that require using asyncio I have been unsuccessful and I was wondering if I am doing something wrong or if it is not possible at all. Thanks.

**Comment by touilleMan** [comment]
Hi @kcfresh53 

AsyncIO (or Trio) requires to run their async loop in a thread. In a regular Python application you would most likely use the main thread for this, but this is not possible for Godot-Python given it's Godot that hold the main thread and only call callbacks on the Python code (so starting an async loop would simply block Godot)

So I think you should start your async loop in it own thread. Of course this means you should be careful when calling Godot API (see https://docs.godotengine.org/en/stable/tutorials/performance/threads/thread_safe_apis.html#doc-thread-safe-apis)

**Comment by kcfresh53** [comment]
thanks, I'll try that.
