### ISSUE TITLE
script autoruns when editor is opened

### ISSUE THREAD

**Issue by JustAnotherGameDevWasTaken** [touilleMan/godot-python#336]
i have a script in the main scene, when i open it in the editor, it starts the script, despite the game not running.

**Comment by TheBricktop** [comment]
Same, i think that this is connected to the way the language server works ie by running python interpreter and executing all the .py files in root for some reason.
im trying to make something like a gate to avoid it running without explicit command.

**Comment by touilleMan** [comment]
When Godot editor ask for Godot-Python to load a script, the Python interpreter does an import on the .py file. Hence everything at the root level of the file is executed (this is needed given after loading the .py file, Godot-Python will retrieve from it the exported class)
This is not an issue as long as you have only declaration in the file, but if you do side effect this can be annoying. Though this is very similar to the `if __name__ == "__main__"` trick you have to put in python scripts to separate declaration code from side effect entry point
