### ISSUE TITLE
Error while installing pycrypto

### ISSUE THREAD

**Issue by tximiss** [touilleMan/godot-python#36]
I can install successfully some libraries while not anothers, for example pycrypto.

`    creating build/lib.linux-x86_64-3.6/Crypto/Signature
    copying lib/Crypto/Signature/__init__.py -> build/lib.linux-x86_64-3.6/Crypto/Signature
    copying lib/Crypto/Signature/PKCS1_v1_5.py -> build/lib.linux-x86_64-3.6/Crypto/Signature
    copying lib/Crypto/Signature/PKCS1_PSS.py -> build/lib.linux-x86_64-3.6/Crypto/Signature
    error: [Errno 20] Not a directory: '/tank/lana/_apps/godot-python-0.9.0/lib/python36.zip/lib2to3/Grammar.txt'
    
    ----------------------------------------
Command "/tank/lana/_apps/godot-python-0.9.0/python-bin -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-18406z3z/pycrypto/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-l85aj1tv-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-18406z3z/pycrypto/
`

**Comment by tximiss** [comment]
I managed to install the library. Forgot to update to Python3.6. 
Sorry.

**Comment by touilleMan** [comment]
you're welcome ;-)
