### ISSUE TITLE
move_and_slide moves all instances of KinematicBody2D

### ISSUE THREAD

**Issue by Difio3333** [touilleMan/godot-python#367]
I'm following the Clear Code Pong Tutorial for Godot on Youtube: https://youtu.be/kr1BoEbuveI and I'm trying to convert that code to godot-python.
To move all my instances of RigidBody2D I use the move_and_slide method. When I run the project all velocities that are applied in 3 different scripts are applied to all RigidBody2Ds.
So the Player moves in a random direction as well as up and down and the ball is moving up and down and in a random direction.
The desired outcome would be that the player moves up and down based on my input and the ball moves in a random direction.
I've made a quick 1 min video displaying my issue: https://youtu.be/SAR6KFySayM
Thanks a lot in advance for your help!

**Comment by niklas2902** [comment]
I think this issue could be caused be similar to #345 .
Could you replace `Vector2.ZERO` by `Vector2(0,0)` and check whether this helps?

**Comment by Difio3333** [comment]
Oh my god Niklas! Thanks so much. I was starting to loose my mind and learn GD-Script because of that.
Needless to say that fixed it. Thanks again for taking the time to write your reply!
