### ISSUE TITLE
Create Games using Godot-Python and Avoid Usage Of Godot Tools

### ISSUE THREAD

**Issue by notzoom** [touilleMan/godot-python#43]
First of all, congratulations for your efforts to add Python support to Godot - huge Python fan here that was looking for something similar.

I have a need however to be able to quickly write a game and execute it without having to open Godot tools. Import the assets from the script etc. and do godot script.py and have it run.

How could that happen ? Thanks !

**Comment by notzoom** [comment]
Any comments ?

**Comment by cridenour** [comment]
Not the author, but I don't believe godot has support for importing assets without the tools. That would be your barrier here - not this library.

**Comment by touilleMan** [comment]
Hi @notzoom, sorry for the late reply

I'm not sure about your need, but as @cridenour said Godot is really an all-integrated engine.
I guess you could use the tool option in script (available in GDscript as well as in Python, see http://docs.godotengine.org/en/3.0/getting_started/scripting/gdscript/gdscript_basics.html#tool-mode) to configure a script that will run inside the editor (as contrary to regular scripts that get run when the game start). This script could then control the engine to do what you want (in your case doing the resources import then closing).
