### ISSUE TITLE
pypy version closes editor on run

### ISSUE THREAD

**Issue by deep-gaurav** [touilleMan/godot-python#46]
When a scene is played with pypy as GDNative Library it closes the editor although the scene runs and works correctly, 

It does not happen when CPython is used.

Tested on Linux amd64, with both Godot master and Godot beta.

**Comment by touilleMan** [comment]
> Tested on Linux arm64

ARM64 ??? really ? That's pretty impressive ;-)

For your trouble, do you have a logs output ?

**Comment by deep-gaurav** [comment]
Lol sorry, that's and 64, I'll update logs

**Comment by touilleMan** [comment]
I would say linux arm 64 would be pretty straightforward (just need to setup a cross compiler and use/build CPython for the platform), but I have no experience with this architecture so I might be missing something there...

**Comment by deep-gaurav** [comment]
![output](https://user-images.githubusercontent.com/28472450/34904230-b20e3336-f867-11e7-825d-19de274cfa24.gif)

more specific error disappears on defocusing it, and I suppose so, on run it changes focus to played scene thus the editor disappears.

I am not sure how to get logs output, 

Here is what I get by using -d and -v flag of godot 

![image](https://user-images.githubusercontent.com/28472450/34904276-aa8a59f4-f868-11e7-8366-9ec6ec567a7f.png)

nothing regarding crash

**Comment by touilleMan** [comment]
Strange... in the log the `PYTHONPATH: [...]` is outputed from Python, which means the dll has been successfully loaded and are running fine.

I see you use the label node, however the [GDnative string API](https://github.com/godotengine/godot/pull/15580) has change recently, so it maybe something like that (should explain the bug in the master branch, but not in the beta2 which doesn't contain this...)

Have you tried to put a `import pdb; pdb.set_trace()` in your python file ? typically at the top of the file (should be hit when the module is loaded) and in your method.

**Comment by deep-gaurav** [comment]
Well it only occurs in pypy version in both beta 2 and master branch of 11th Jan,.  
script does is working fine as label text and scale changed. 

Strangely on adding import pdb;pdb.set_trace() the script stopped working and text didnt changed nor did label and editor did crashed like before

![image](https://user-images.githubusercontent.com/28472450/34905823-ae381f46-f886-11e7-9935-97382b25aa00.png)
Error that I received, just one line from scrip outputted

**Comment by touilleMan** [comment]
I've fixed some memory leaks that could have been the cause of this (but it is related to https://github.com/godotengine/godot/pull/15761 which is not yet merged...)

**Comment by deep-gaurav** [comment]
I cannot reproduce this issue on any other project with latest godot-python and Godot. Although it still exist in that project. I could've misconfigured something.

**Comment by touilleMan** [comment]
Perhaps you can send me this project so I can try it ?

You can send it on my email if you don't want it to be public on this issue
page

**Comment by deep-gaurav** [comment]
Never mind, it's solved, I was cleaning old .gdnlib and .gdns files to mail you and deleting them solved problem, seems I misconfugured pythonscript.gdnlib file(it wasnt provided earlier),

**Comment by touilleMan** [comment]
:+1:
