### ISSUE TITLE
Status of the project for production

### ISSUE THREAD

**Issue by notzoom** [touilleMan/godot-python#47]
I am wondering what is the status of the project for production.

Huge Python fan here who would love to use this instead of GDScript.

**Comment by touilleMan** [comment]
Hi,

It depend what you call production, Godot 3 is itself not stable right now so strictly speaking nothing built on it (like godot-python is) should be considered "stable for production".

That said, Godot-Python codebase works pretty well.
Downsides are API changes in GDNative which cause regressions (remember Godot 3 is not final so this is perfectly normal) and multiplatform testing (I'm developing the project on linux 64bits and windows is a really exotic target so a lot can go wrong there...).

What I would recommend you is waiting for v1.0 of Godot-Python to be released before doing anything big with it.
My current objective for v1.0 is basically to wait for Godot 3.0 final to have a stable GDNative API and make sure windows build are working properly.
 
One good thing however is Godot support mixing different scripts language in a single project. So if you're not confident enough you can start your project in GDscript, then convert to Python one file at a time (should be pretty easy given the API is the same and both language similar) once the project has grown on maturity.
