### ISSUE TITLE
Some failed tests

### ISSUE THREAD

**Issue by Ertain** [touilleMan/godot-python#51]
On the Discord channel, @touilleMan asked me to post some information about failed tests I encountered while testing the module. So here's some of the information he wanted.

If I recall, this was the configuration I used to build the engine:

    scons platform=x11 gdnative_wrapper=yes target=release_debug tools=yes

The command I used to build the module:

    scons platform=x11-64 backend=cpython godot_binary=/home/user/code/godot-master/bin/godot.x11.opt.64 gdnative_wrapper_lib=/home/user/code/godot-master/bin/libgdnative_wrapper_code.x11.opt.64.a

Command I used to test it:

    scons platform=x11-64 backend=cpython godot_binary=../godot-master/bin/godot.x11.opt.tools.64 gdnative_wrapper_lib=../godot-master/bin/libgdnative_wrapper_code.x11.opt.64.a test

And the output from the test, found [here](https://www.pastebin.ca/3964533).

**Comment by touilleMan** [comment]
Thanks for the report :+1: 

The output is just as expected: the `x` and `X` marked expected failures in tests, and the ERROR and WARNING logs at the end are due to memory leaks while detected by Godot on closing, which are tracked by issue #26.
