### ISSUE TITLE
Can't return string from function

### ISSUE THREAD

**Issue by Ertain** [touilleMan/godot-python#52]
I'm trying to use this wonderful code, but I can't seem to do the simplest things.

I have the following Python code:

```
from godot import exposed, export
from godot.bindings import TileMap
from random import choice, randint

@exposed
class Thing(TileMap):

    names = ["Mike","Bill", "James", "Robert"]

    thing1 = "Hi, I'm thing1."
    thing2 = "Hi, I'm thing2."
    some_number = 0

    def fly(self):
        print("Go fly a kite!")

    def get_name(self):
        name = choice(self.names)
        return name
    
    def do_number(self):
        self.some_number = randint(1,10)
    
    def get_number(self):
        return randint(1,10)
        
    def get_that_guy(self):
        b = "It's the man! Run!"
        return b
```

When I use the function which returns a number (in this case, an integer), it works fine. But when I try a string, it doesn't work. So I have this code:

```
extends Node2D

func _ready():
    var b = get_node("py_code")
    print("The random number chosen is %s." % b.get_number)
    print(b.get_that_guy())
```
It prints out "The random number is 5.", but it doesn't print "It's the man! Run!" So I am at a loss as to why my strings are not being returned from the function. FWIW, I am using Godot 3.0 alpha (_very_ recent version) with recent Python bindings.

**Comment by touilleMan** [comment]
[project-issue-52.zip](https://github.com/touilleMan/godot-python/files/1679711/project-issue-52.zip)

I couldn't reproduce your issue (see the enclosed project): 

```
➜  project-issue-52 git:(master) ✗ ~/projects/godot-python/godot/bin/godot.x11.tools.64 
OpenGL ES 3.0 Renderer: Mesa DRI Intel(R) HD Graphics 520 (Skylake GT2) 
GLES3: max ubo light: 409
GLES3: max ubo reflections: 455, ubo size: 144
ARVR: Registered interface: Native mobile
Pythonscript version: 0.10.0
Pythonscript backend: cpython 3.6.3 (v3.6.3:2c5fed8, Jan 27 2018, 11:13:18)  [GCC 5.4.1 20160904]
PYTHONPATH: ['/home/emmanuel/projects/godot-python-release/examples/project-issue-52/pythonscript/lib/python36.zip', '/home/emmanuel/projects/godot-python-release/examples/project-issue-52/pythonscript/lib/python3.6', '/home/emmanuel/projects/godot-python-release/examples/project-issue-52/pythonscript/lib/python3.6/lib-dynload', '/home/emmanuel/.local/lib/python3.6/site-packages', '/home/emmanuel/projects/godot-python-release/examples/project-issue-52/pythonscript/lib/python3.6/site-packages', '/home/emmanuel/projects/godot-python-release/examples/project-issue-52/', '/home/emmanuel/projects/godot-python-release/examples/project-issue-52/lib']
The random number chosen is 9.
It's the man! Run!
```

I'm using Godot 20a52aa39db9a6e35738ee486848bd3dd28510cb (from 30/01) and last master of godot-python (8f852d5978260ab5e991265eb994f8e17343c9c4) with CPython backend

Have you checked if the log is print on stdout instead of on the Godot console ? have tried to put a breakpoint in `get_that_guy` to make sure it is called (and not crashing) ?

**Comment by Ertain** [comment]
I'm on Linux Mint 18.2.

Strangely, the project you gave me worked. However, something in my setup was borked, so I had to scrap it, and build from sources. Now I've com across something just as strange.

When I use the following python code:
```
from godot import exposed, export
from godot.bindings import TileMap
from random import choice

@exposed
class Thing(TileMap):

    names = ["Mike","Bill", "James", "Robert"]

    def get_name(self):
        name = choice(self.names)
        return name
```
With the following GDscript code:
```
extends Node2D

func _ready():
    var b = get_node("py_code")
    # print(b.get_name())
    print("The name randomly chosen is %s." % b.get_name())
````
All that it prints out to the Output Inspector is `The name randomly chosen is .`

I don't know where _this_ behavior is coming from. Btw, the binary I built is the Godot Engine 3.0 stable version, without the Mono bindings.

**Comment by touilleMan** [comment]
I would suspect a memory corruption with godot's String or StringName...

**Comment by Ertain** [comment]
Good, now all we need to do is correct it. So, how do we do that? Would it help to get a trace of some kind when I run the code?

**Comment by deep-gaurav** [comment]
A memory correction isn't that easy to tackle AFAIK, a possible workaround IMO could be to have a variable in your python script, and assign string to it, then access it from your gdscript code.,

**Comment by Ertain** [comment]
Wow, that was fast.

Anyway, yeah, I was sort of thinking of trying that workaround, @deep-gaurav.

**Comment by touilleMan** [comment]
> A memory correction isn't that easy to tackle AFAIK, a possible
workaround IMO could be to have a variable in your python script, and
assign string to it, then access it from your gdscript code.,

This is a good test to do. When passing arguments between python and Godot
a conversion occurs so I assumed memory isn't shared between the two,
however I could be wrong (which would lead to undefined behaviour such as
this one)

**Comment by touilleMan** [comment]
I've retry with your new snippet (https://github.com/touilleMan/godot-python/issues/52#issuecomment-362110824) and I don't have the trouble...

I've also noticed that if `get_name` returnrs `None`, then the string outputed is `The name randomly chosen is Null.` so as you said on discord it's most likely an empty string which is return by the function (or the conversion of the python string into a godot one result in an empty godot string...)

**Comment by touilleMan** [comment]
I've tracked a potential error in the code that could explain your issue (see eb844113252ed089e2a9aeb224eddf54cf33dbd7)
Basically the variant returned has it destructor called when python garbage collects it. However this object has been passed by copy to Godot (which should be the one calling the destructor when he no longer use it !).
This is fine for object living purely inside the variant (like int, bool etc.) but not for ones allocating data on the side (like array, dict or strings)

So can you re-compile your pythonscript module and tell me if it solve the issue ? ^^

**Comment by Ertain** [comment]
From the looks of it, that bug fix did solve the issue.

When I use the following Python code:
```
class Thing(TileMap):
   names = ["Mike","Bill", "James", "Robert"]

   def get_name(self):
       return choice(self.names)
```
in GDscript:
```
func _ready():
    var b = get_node("py_code")
    print("The name chosen in Godot is %s." % b.get_name())
```
It prints out the sentence `The name chosen in Godot is Robert.`

**Comment by touilleMan** [comment]
The bug is dead, long live King Robert !!! \o/

![long live king robert](https://i.stack.imgur.com/uwi3K.jpg)
