### ISSUE TITLE
Need more info to start godot-python

### ISSUE THREAD

**Issue by jamad** [touilleMan/godot-python#55]
I am interested in this project because I want to use general python modules in Godot.
I visited the page https://github.com/touilleMan/godot-python and saw Quickstart to visit https://github.com/touilleMan/godot-python/releases.
Because all I could see there was the link to the file , I dowloaded windows-64 zip and extracted it.
Then moved those folders into my Godot project to see the folder not recognized by Godot.
I wish I could see some exact steps in the description for Quickstart or Wiki here.
Thanks.

**Comment by touilleMan** [comment]
Hi,

You should have a look at the [pong example](https://github.com/touilleMan/godot-python/tree/master/examples/pong).
All you should have to do is to drop the `pythonscript` folder (depending of your platform) into this folder.

Take note that the release builds may be out of date and you may want to build them yourself (look at the travis and appveyor links on the README to see how to do it)

**Comment by jamad** [comment]
Thank you very much, @touilleMan. I will try it and such info would be nice to be seen in Quickstart.
