### ISSUE TITLE
Rename mv to move for the Windows-Build

### ISSUE THREAD

**Issue by Nophlock** [touilleMan/godot-python#65]
Hello,

while trying to compile the newest source code for myself, the cmd-prompt stumbled across the error, that it couldn't find the "mv" command. After I took a look in the corresponding file, and changed "mv" to "move", which is the windows equivalent of the mv command from linux, it compiled fine. Since I don't know how to send an PR and all the other stuff that is related to github, I thought I just tell it this way :P

https://github.com/touilleMan/godot-python/blob/0095c70dc4d5a5ffac9ceb6bb48c535014295d58/platforms/windows-64/SCsub#L56

**Comment by touilleMan** [comment]
Thanks for the report !

I'm not an expert about windows platform, but it seems [appveyor works fine with the current scons script](https://ci.appveyor.com/project/touilleMan/godot-python/build/1.0.233/job/5juns6bkhw0uegfd#L47) (so with this `mv` command). Do you have any idea why this is the case ? I would guess appveyor setup common alias to help unix developer such as myself, but this is the type of things I would like to be sure before touching this...

Considering how to create a PR, you should [have a look here](https://help.github.com/articles/fork-a-repo/), the nice thing about submitting a PR is you will get fame for eternity by having your name in the authors.txt of the project 😄

**Comment by garyo** [comment]
A good way to do this cross-platform is to avoid cp and mv altogether and use the SCons Copy and Move action-factory methods. See http://scons.org/doc/production/HTML/scons-user/ch12s03.html

**Comment by touilleMan** [comment]
@Nophlock I've had a second look at this command and it appears it was a hack to avoid having to recompile cpython everytime a change is done in godot-python (saved me a lot of time while I was debugging the windows build...). There is no need for this now, so the trouble should disappear by itself once 237778f87cefc28481e7980a844782cdcf23b19c will get merged :+1: 

@garyo totally agree, however I don't know how to combine scons Copy and Move action-factory with a the Command one. Ideally I should have the Command action in a target depending of another target with the Copy/Move action, however scons only works with real target in file system (beside target `/foo` cannot depend of `/foo/bar`, which make this requirement even more problematic...). That's the reason why I have those big and ugly Command action containing a lot of script altogether...

**Comment by Nophlock** [comment]
@touilleMan Thats nice to hear. I will give it a try after it got merged.

**Comment by touilleMan** [comment]
@Nophlock the merge has been done ;-)
