### ISSUE TITLE
which version can run in windows?the example Already tested

### ISSUE THREAD

**Issue by xyzdh** [touilleMan/godot-python#66]
1.godot
2.godot-python release

**Comment by touilleMan** [comment]
Hi xyzdh,

Can you be more specific ?

If you want to build the project for windows, I suggest you have a look at the [appveyor builds](https://ci.appveyor.com/project/touilleMan/godot-python/branch/master/job/f9tt3xkh9s0adw3m)

If you feel like it's too complicated, fear not ! I'm working on providing Godot Python on the Godot AssetLib, once this is done their would be not more need for complexe compilation (just one click install from the Godot editor :smile: )

**Comment by xyzdh** [comment]
Thank you so much for doing this。I look forward to getting the lib from the Godot AssetLib
