### ISSUE TITLE
how to solve it. when run the example,it crush...

### ISSUE THREAD

**Issue by xyzdh** [touilleMan/godot-python#67]
![default](https://user-images.githubusercontent.com/8004536/37401612-96b7238c-27c3-11e8-95c5-c5e2e14c8eab.png)

**Comment by garyo** [comment]
Run that godot in Visual Studio with those args (`--path D:/pong --editor`); you might get a better stack trace there. If that doesn't work, build godot yourself with debugging symbols (the default).

**Comment by touilleMan** [comment]
Do you use Godot Python builds from the release page ?
They are pretty outdated, so it's possible the problem comes from incompatible GDnative API version with newer Godot release...
