### ISSUE TITLE
Donation

### ISSUE THREAD

**Issue by notzoom** [touilleMan/godot-python#71]
Hello, would a donation to the project help it advance ? If so, how is it possible ? 

I've been waiting for a long long time for Python to meet real game development and this is the best opportunity, by far.

**Comment by touilleMan** [comment]
Hi !

Thanks a lot for your willingness to support the project !
As you surely suspect I'm working on this project only on my free time (which is really thin those days unfortunately 😢 ), I and don't plan to change this for the moment.
For those reasons, I don't think it would be good to accept money for this project (I would add pressure on me to work, and I couldn't guarantee anything regarding the evolution of the project).

If you want to help the project, I would suggest to start playing with the project, read the code (almost everything is in python 😄 ) and try to make PR or even just discuss design choices here.
If you need help check the [godot discord](https://discordapp.com/channels/212250894228652034/416283125170176000) I'm pretty often there.

Aaaand if you still want to donate, I would suggest to [give to the main Godotengine team](https://www.patreon.com/godotengine), they are an awesome band of folks and deserve any cent you can spare ;-)
