### ISSUE TITLE
PackedScene Memory Leak

### ISSUE THREAD

**Issue by craig-r-ciccone** [touilleMan/godot-python#92]
I'm running through the Godot step by step tutorial series using the windows-64-cpython version of godot-python. When I got to the instancing portion of the tutorial I noticed unusual slowness in my application. After some debugging I noticed that the memory utilization was growing endlessly.

The application itself is pretty simple. Its a main scene with a PackedScene (a ball) that is instanced every time the mouse is clicked. The ball has a VisibilityNotifier2D child that calls queue_free when it exits the screen. Side note here, I'm not sure if I am pulling in PackedScenes properly in my python script as I didn't see this done in any of the examples, but here are the python scripts:

```
@exposed
class Main(Node):

    Ball = ResourceLoader.load('res://scenes/Ball.tscn', 'PackedScene', False)

    def _input(self, event):
        if event.is_action_pressed("click"):
            new_ball = self.Ball.instance(0)
            new_ball.position = self.get_viewport().get_mouse_position()
            self.add_child(new_ball, False)
```

```
@exposed
class Ball(RigidBody2D):

    def _on_visibility_screen_exited(self):
        self.queue_free()
```

And here are their GD script equivalents:

```
extends Node

export (PackedScene) var Ball

func _input(event):
	if event.is_action_pressed("click"):
		var new_ball = Ball.instance()
		new_ball.position = get_viewport().get_mouse_position()
		add_child(new_ball)
```

```
extends RigidBody2D

func _on_visibility_screen_exited():
    queue_free()
```

It appears the the issue is with calling queue_free from python. When I swap the GD script for the ball (RigidBody2D) with its python equivalent, then memory utilization is normal. Otherwise when using godot-python, memory utilization grows with every new instance of the ball and is never freed. Here's a screenshot of the memory utilization climbing each time new instances of the PackedScene are added:

![godot-py-mem-leak](https://user-images.githubusercontent.com/36709314/39096450-4eba9450-461e-11e8-9cab-e5b5dfe0c4e9.PNG)

**Comment by paolobb4** [comment]
Very good job finding the source of the problem there @craig-r-ciccone :+1:
@touilleMan I think this is due to `node.queue_free()` (actually `node.free()` since `queue_free()` only put's the object in a queue to latter be freed) being lazy_binded rather than explicitly defined and therefore godot-python doesn't know to let go the gdobj for godot's garbage collector to take care of it when `queue_free()` is called.
I think this might be the first function that actually requires to be explicitly defined (or rather wrapped next to a call to `gc_protector.protect_from_gc.unregister()`, we don't need to make things more complicated than needed :sweat_smile: ), unless I missed something else in the src that has to be fixed.

**Comment by touilleMan** [comment]
@paolobb4 I've check with gdb, python correctly call `Node::queue_delete`. And the object is correcly freed by `SceneTree::_flush_delete_queue` later on (see https://github.com/godotengine/godot/blob/1c419531a009f48aa074f9b5f93b98d387c33723/scene/main/scene_tree.cpp#L1070-L1076)
 
However it seems temporary Godot objects are not freed at all (in the example `self.get_viewport()` returns a Python `godot.bindings.Viewport` instance which binds on a godot `Viewport`, when the Python instance is freed, it doesn't try at all to free the godot object...).
I've notice differents memory leaks pattern depending on if the scene is only instantiated (low memory leak, object count grows) or also added to the parent scene (high memory leak, object count stay stable).

Anyway this issue show the current memory management of Godot objects is broken. My guess is we should store the object along with a variant instance that will be release when the Python wrapper instance is destroyed.

**Comment by touilleMan** [comment]
@craig-r-ciccone f3d70f4fcf88c865fc7b3b7ac9cf09f8c503a1aa has improved a lot memory management, can you retry with the last master to see if the issue is still present ?

**Comment by craig-r-ciccone** [comment]
@touilleMan thank you! I just built from master and tested this out and the memory management is working as expected.
