### ISSUE TITLE
[Help] How do I setup on a linux machine through Assetslib

### ISSUE THREAD

**Issue by orendanniel015** [touilleMan/godot-python#99]
Hello everyone, 
I am trying to setup godot-python(PyPy) in my project.
In the readme.md it is said that the simplest way is just to install it through Assetslib, after installing the package godot creates folder named "pythonscript" and a file named "pythonscript.gdnlib".
I also have PyPy and CPython installed.

Now after doing all of that what do I do? When I try to add a script there is no python option
Thanks for the help!

**Comment by touilleMan** [comment]
Hi,
First note you don't need to have Pypy or CPython installed given Godot-Python ships with it own interpreter isolated from the rest of your system (it won't use the PYTHONPATH env var for instance)

Once installed, all you should do is to restart Godot and then you should be able to select Python in the new script dialogue.
If it's still not working, can you remove `pythonscript` and `pythonscript.gdnlib` and install the cpython flavour of godot-python to see if the behavior is the same

**Comment by orendanniel015** [comment]
Hello touilleMan 
First let me thank you about the quick response
I have deleted `pythonscript` and `pythonscript.gdnlib` and after that I installed the cpython version then I have restarted godot and tried to apply a new script and I still can't see a python option.
What should I do now?
BTW I am running godot v3.0.2

**Comment by touilleMan** [comment]
I've just tried with godot's last master with a clean project and it works fine.
However I'm doing my tests on Linux, what platform are you on ? (macOS is the least tested given I don't have this platform available...)

**Comment by orendanniel015** [comment]
Arch linux, the godot AUR build

**Comment by orendanniel015** [comment]
I found the problem I installed godot via the AUR, but now I have reinstalled godot using the executable found in there website and now it works

**Comment by touilleMan** [comment]
@orendanniel015 thanks a lot for making the light on this ^^

I guess it's more an issue for the package maintainer then
